### ISSUE TITLE
Count triggers per object and highlight if there is more than one unmanaged trigger

### ISSUE THREAD

**Issue by dschach** [SalesforceLabs/OrgCheck#102]
More of a best-practice check, but can be a big problem for some orgs. Should only have one unmanaged trigger per object.

Could also have a table of all triggers, with a column for trigger name, object name, and each of the trigger contexts (with a checkmark if the trigger fires in that context).

**Comment by VinceFINET** [comment]
Very interesting. I got the idea from another user as well. So maybe a second tab to show objects that have at least one trigger unmanaged. With a bad score if the count is two or more. It should have a column with the triggers involved for each object so that you can click on them.

**Comment by VinceFINET** [comment]
Dear @dschach , i thought about this request and it could be something like the following:

Here you see two active triggers for the same object (but not the same scope one is before update and the other is after update):
![image](https://user-images.githubusercontent.com/3799275/120174173-15b8f500-c205-11eb-8b43-d6f7cef9ad82.png)

I added a thrid sub-tab to list the number of active triggers for each object :
![image](https://user-images.githubusercontent.com/3799275/120174255-2cf7e280-c205-11eb-97f8-8d24dcf9e4d6.png)

What do you think?

**Comment by pritaunk** [comment]
this is going to be super useful! I like the additional info you have added like contains DML etc. 
I think there's one I posted about flagging if a trigger has logic written within, and if it has more than a certain # of characters to help identify if it has logic or not.

**Comment by dschach** [comment]
This looks really good!
