### ISSUE TITLE
Report of Profile/Perm set giving access to Objects, Fields, and Apps

### ISSUE THREAD

**Issue by sudhird7** [SalesforceLabs/OrgCheck#104]
**Is your feature request related to a problem? Please describe.**
My current challenge is that for each project, if there is no technical documentation, I have to do a data loader export to get data such as which profiles/permission sets are giving access to objects, fields, and apps as well as how many users are assigned to each profile/perm set. While there are tools that give user counts for profile/perm set there is no "one view" tool.

**Describe the solution you'd like**
Ideally the results would be showed in a tabular format listing:

1. For Objects: Profile name, permission set name, object label, object API names, CRUD permissions, View All, Modify All
2. For Fields: Profile name, permission set name, field label, field API  name, read permission, edit permission
3. For Apps: App label, app api name, Profile Name, # users assigned to profile, permission set name, # users assigned to permission set.

Extra cherry on the top would be to have the lists filterable.

**Describe alternatives you've considered**
running a data loader export for every project

**Comment by VinceFINET** [comment]
For fields access, we should rely on the table called "FieldPermissions":
```
SELECT Field, Id, ParentId, PermissionsEdit, PermissionsRead, SobjectType, SystemModstamp 
FROM FieldPermissions
```

**Comment by sudhird7** [comment]
> For fields access, we should rely on the table called "FieldPermissions":
> 
> ```
> SELECT Field, Id, ParentId, PermissionsEdit, PermissionsRead, SobjectType, SystemModstamp 
> FROM FieldPermissions
> ```

Agreed! I use ObjectPermissions qyery for object permissions as well. Here are the two queries i'm currently using:

**Object Permissions:**

`SELECT Parent.Profile.Name, Parent.Label, Parent.IsOwnedByProfile, SobjectType, PermissionsRead, PermissionsCreate, PermissionsEdit, PermissionsDelete, PermissionsViewAllRecords, PermissionsModifyAllRecords FROM ObjectPermissions ORDER BY Parent.Profile.Name, Parent.Label, SobjectType`

**Field Permissions:**

`SELECT Parent.Profile.Name, Parent.Label, Parent.IsOwnedByProfile, SobjectType, Field, PermissionsEdit, PermissionsRead FROM FieldPermissions ORDER BY Parent.Profile.Name, Parent.Label, SobjectType, Field`

**Comment by VinceFINET** [comment]
Very interesting and when I see the isownedbyprofile field being used I guess that your two queries are working for profile and permission set !!!

very very interesting !! Thanks for sharing!

**Comment by sudhird7** [comment]
Yes, exactly! Some orgs are moving from profiles to perm sets following Salesforce recommendation so access is now split between the two, so I felt it was important to list out what's giving which access to objects and fields. Same would be the case for Apps.

**Comment by VinceFINET** [comment]
OK so I am prototyping the Object CRUD page.
For now it looks like this as a tabular table.
![image](https://user-images.githubusercontent.com/3799275/122287336-1df57d80-cef1-11eb-8bbc-7627195341ac.png)

I am a little confuse about how to present that page better.
Would it be better to have a matrix but what about orgs with a LOT of objects (if we assume that the matrix has columns for each SObjectType)....

Would you prefer to have a picklist to filter the objects to show (like via package selections).

Tell me...

**Comment by sudhird7** [comment]
I have the same issue. I ended up putting a dropdown for object selection and then retrieve info for that object. I'm planning something similar for profile/perm set centric view: let them select a profile/perm set and then bring back all the objects (with the CRUD/VA/MA) and display in table. otherwise it will become a mess for the user, i think. HEre's what I have for object-centric view:

<img width="2701" alt="2021-06-16_16-43-00" src="https://user-images.githubusercontent.com/2053959/122290971-4ca82f80-cec2-11eb-9306-5eec1aa27611.png">

**Comment by VinceFINET** [comment]
Ok so two views in your illustration. One to check all the cruds of a specific profile perm set across all objects. The other to check all the crud of a specific object across all profile and perm sets.

**Comment by VinceFINET** [comment]
Maybe a specific new tab for cruds would be good then. What do you think?

**Comment by VinceFINET** [comment]
Splitting this ticket (you were right @sudhird7 !!!) into three tickets:
- #109 for apps
- #108 for fields
- #107 for objects
