### ISSUE TITLE
Shield encryption Info

### ISSUE THREAD

**Issue by sfvenkat** [SalesforceLabs/OrgCheck#106]
Would be good to have a Tab in Orgcheck that lists shield encryption info.

that would need to be dynamic because the field IsEncrpyted is only there if you have PE so i need to figure out this. Maybe an option in the Home Tab....

**Comment by VinceFINET** [comment]
Thank you for this idea.
At this time OrgCheck does not require additional products nor licenses.

I will put this idea in incubation
Please note that I have created a separated project (couple of years ago) in my github https://github.com/VinceFINET/Shield-Encryption-Report, that you might be interested in!

**Comment by VinceFINET** [comment]
While reviewing this ticket i found a bug here:
```
{ name: '{!JSENCODE($Label.OrgCheck_Encrypted_CL)}', property: 'unique', formula: (r) => { return helper.html.render.checkbox(r.unique); }},
{ name: 'Unique', property: 'encrypted', formula: (r) => { return helper.html.render.checkbox(r.encrypted); }},
```

here the name on the column dores not correspond to the data.

**Comment by VinceFINET** [comment]
See here: 
<img width="184" alt="image" src="https://user-images.githubusercontent.com/3799275/207687988-61c99f1a-8495-41c7-8286-eee54a3ce66b.png">

and here:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3799275/207688070-dd609695-5087-4a31-8eef-f8c3b870d696.png">

The two pages are now coherent.

**Comment by VinceFINET** [comment]
But I display encrypted ONLY on the Object / Field page.
Not on custom field page.

Let's create a field encrypted on Account and see what happens:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3799275/207688795-a03f6386-2206-498e-894e-29fb20d960a8.png">

Yeah not possible at this time to get easily if the field is encrypted via Shield.

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/3799275/207699611-fdd3b41f-c111-4056-a8a6-71a37c47f67d.png">

The option would be to get one by one the Metadata information and check if the attribute "Metadata.encryptionScheme" is there....

**Comment by VinceFINET** [comment]
so encrypt info is on the object page.
let's say the job is done!

**Comment by VinceFINET** [comment]
oppps forgot to commit my change!!
