### ISSUE TITLE
Add Custom Metadata Types and Custom Settings to OrgCheck - with scores

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceLabs/OrgCheck#116]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Include Custom Metadata Types, with # records, dependency (if available!) and score.  Also include Custom Settings with dependency.

**Describe alternatives you've considered**
Setup > Custom Code > Custom Metadata Types > pick through each to see number of records (CMT list view doesn't show)
Setup > Custom Code > Custom Settings > list view shows number of records, but not dependency

**Additional context**
This would be very handy for org reviews and admins getting a good knowledge about their org

**Comment by VinceFINET** [comment]
![image](https://user-images.githubusercontent.com/3799275/139056696-4211467a-32ee-4e89-9615-58299cc3d5c3.png)

Done @charles-thompson-salesforce-com !
