### ISSUE TITLE
Error trying to see OrgCheck

### ISSUE THREAD

**Issue by alekuo** [SalesforceLabs/OrgCheck#118]
**Describe the bug**
In https://google-youtube-devices--shguat.lightning.force.com/, I get an error when I try to see tabs in OrgCheck app. I am a System Administrator in the org.

**To Reproduce**
Log into https://google-youtube-devices--shguat.lightning.force.com/, locate OrgCheck app and select it. Home will load, but Objects and other tabs will through this error.

Please see the error message below.
Thank you!
-Alena Chaika

--------------
Please go here and log an issue with the following information.

OrgCheck Information
Version: v1.9.5
Installed on OrgId: 00D7d0000077hkT

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
User Agent: Mozilla/5.0 (X11; CrOS x86_64 13904.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.147 Safari/537.36
Operating System: Linux x86_64
Language: en-US

Error #0: INVALID_SESSION_ID
When: While creating a promise to call "private_query".
What:
index: 1
queryMore: undefined
queryString: SELECT NamespacePrefix FROM Organization
queryUseTooling: false
Stack:
INVALID_SESSION_ID: This session is not valid for use with the REST API
   at h.getError (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1626865218000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1626865218000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1626865218000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1626865218000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1626865218000/orgcheck__OrgCheck_JSForce_SR:4:9798)

**Comment by VinceFINET** [comment]
are you assigned to the permission set contained in the package?
i believe it's called "OrgCheck Users"

**Comment by alekuo** [comment]
So, yes I did not have that permission set assigned to me. I assigned it to myself after your note and re-logged in. However, the issue still persists.
I can see Custom Fields, Automations, Custom Labels, and Visual Components tabs, but on all other tabs I get the same error as above.
Anything else I can do? Thank you!
-Alena

**Comment by VinceFINET** [comment]
You should have the permission "API Enabled" can you check that??
![image](https://user-images.githubusercontent.com/3799275/127190982-0122c958-f488-45c1-b6f2-14d3fe06c044.png)

**Comment by VinceFINET** [comment]
forget my previous comment as soon as you have the OrgCheck permission you should have it.

When I check the "datastore" that we have in OrgCheck i see the following table below.

I suspect that if the page is using a datastore that uses the REST API you have the error in your case...
So why can't you use the REST API where you can use the Tooling API ????

| Datastore | Use Tooling API? | Use REST API? |
| -- | -- | -- |
| Workflows | true | false |
| Flows | true | false |
| Packages | true | true |
| CustomLabels | true | false |
| CustomSettings | true | false |
| VisualforcePages | true | false |
| VisualforceComponents | true | false |
| ApexClasses | true | true |
| ApexTriggers | true | false |
| StaticResources | true | false |
| LightningPages | true | false |
| LightningWebComponents | true | false |
| AuraComponents | true | false |
| Profiles | false | true |
| ObjectCRUDs | false | true |
| ProfileLoginRestrictions | true | true |
| PermissionSets | false | true |
| ... | ... | ... |

**Comment by VinceFINET** [comment]
can we set up a call?

**Comment by VinceFINET** [comment]
it reminds time when we had a permission on the user about accessing APIs
![image](https://user-images.githubusercontent.com/3799275/127194434-3cba415d-a937-4aef-90b0-ca7a641c7479.png)

do you have such a thing on your salesforce user setting???

**Comment by VinceFINET** [comment]
another lead...

do you have on your profile the following setting:
Profile -> Session Settings -> "Session Security Level Required at Login-High Assurance"

**Comment by alekuo** [comment]
Hello! 
Sorry I did not reply quickly, yes I would love a call! After 11 am MST is fine today (Wed) or the rest of the week.
Let me answer your messages: 
- API Enabled is TRUE on my profile (System Administrator)
- Not sure about the REST API vs Tooling API. We can look into it during a call?
- Use Any API Client is a setting on the profile, it is currently FALSE.
- Session Security Level Required at Login is set to NONE.

I have OrgCheck working fine in another org not related to this one. These settings are the same there, and I don't even have OrgCheck Users permission set assigned to my user there.

Thank you!
-Alena

**Comment by alekuo** [comment]
FYI: I enabled "Use any API Client" through a permission set for my user, and it started working. The only thing that is strange is that in the other sandboxes of a different org, I have no permission set assigned at all, and it works just fine.

**Comment by VinceFINET** [comment]
@alekuo 
Take a look at this article https://salesforce.stackexchange.com/questions/235829/is-there-a-difference-between-the-use-any-api-client-and-api-enabled-permiss
I believe in the org 00D7d0000077hkT (where OrgCheck was not working), you might have activated the feature "API Client Whitelisting".
It seems that when you activate this feature, to run orgcheck you need to assign your user this additional permissione called "Use any API Client" which appears ONLY in the case where "API CLient Whitelisting" is enabled in the first place.

:)

**Comment by VinceFINET** [comment]
Does it resolve your issue, @alekuo ???

**Comment by VinceFINET** [comment]
I added this information in the documentation. Thank you @alekuo  !!!
