### ISSUE TITLE
Automations Error

### ISSUE THREAD

**Issue by jdayment** [SalesforceLabs/OrgCheck#120]
**Describe the bug**
When clicking on the automations tab I recieved the following.

**To Reproduce**
OrgCheck Information
Version: v1.9.5
Installed on OrgId: 00D4C000000LPuh

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 1322
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '3013i0000009axzAAA'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at h.getError (https://ANONYMIZED_MYDOMAIN.sandbox.vf.force.com/resource/1628694404000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at https://ANONYMIZED_MYDOMAIN.sandbox.vf.force.com/resource/1628694404000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (https://ANONYMIZED_MYDOMAIN.sandbox.vf.force.com/resource/1628694404000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at https://ANONYMIZED_MYDOMAIN.sandbox.vf.force.com/resource/1628694404000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (https://ANONYMIZED_MYDOMAIN.sandbox.vf.force.com/resource/1628694404000/orgcheck__OrgCheck_JSForce_SR:4:9798)

**Comment by VinceFINET** [comment]
Duplicate see #74
