### ISSUE TITLE
OrgCheck --> Objects - Tables are replicated

### ISSUE THREAD

**Issue by rangaraj** [SalesforceLabs/OrgCheck#122]
**Describe the bug**
The tables in the output of some objects are replicated. 
<img width="1358" alt="Screen Shot 2021-09-08 at 6 36 52 PM" src="https://user-images.githubusercontent.com/1404537/132607909-1f6e8509-cc7b-4c70-9f59-7c7b272e8b49.png">

**To Reproduce**
Navigate to the Objects tab.
Select "No Package", "Opportunity"

There is no error, just duplicated data.

**Comment by VinceFINET** [comment]
can you share the FS that you have on opportunity? i don't have any in my dev org, and need to reproduce.
maybe only two FS is enough to reproduce??

**Comment by VinceFINET** [comment]
I tried to reproduce but it seems to work on my side....
let me show you

in the setup menu:
![image](https://user-images.githubusercontent.com/3799275/132639175-8353d39a-f327-44df-a7c2-d8382c6d9b4f.png)

 
in org check:
![image](https://user-images.githubusercontent.com/3799275/132639098-93d6fd60-6fb1-4557-9d72-236ca3dfadbe.png)


certainly something we missed in your context?!

**Comment by rangaraj** [comment]
Here are the FieldSets...
![image](https://user-images.githubusercontent.com/1404537/132789296-3510969f-323f-4980-be25-161258494596.png)

**Comment by VinceFINET** [comment]
I don't know if this is the same reason but today i discovered in a DE that I reproduce the issue you have. All tables are duplicated in this page.
I'll work on it and hopefully this will solve your issue as well.

**Comment by VinceFINET** [comment]
Found!!! I could reproduce your issue....
Do you happen to have a custom metadata type that is also called "Opportunity"?
In my case that was causing the issue.
Renaming the custom metadata type solved the issue. But of course i will change the code.
