### ISSUE TITLE
Object Limits displayed on Object page does not match Object Manager --> Object Limits page

### ISSUE THREAD

**Issue by rangaraj** [SalesforceLabs/OrgCheck#123]
**Describe the bug**
Object Limits displayed seem different from what the Object Manager --> Object Limits page. 
Unable to correlate the information displayed. There are atleast 6 sets of limits but none for object with Prefix 006.

**To Reproduce**
Check the 
Org Check Object detail page for "No Package", "Opportunity"
![image](https://user-images.githubusercontent.com/1404537/132608612-e5c8f294-7727-45cb-9fe2-d41541234754.png)

Now check the Object Limits from the Setup page for the same object...
![image](https://user-images.githubusercontent.com/1404537/132608733-991f69dd-2b8f-4ba0-be21-fca70232fe75.png)

**Comment by VinceFINET** [comment]
@rangaraj 
do you have packages installed that alters the opportunity object?
i am wondering if the limits that I get from the API is not limited to the core scope and not the packages added limit....

**Comment by rangaraj** [comment]
@VinceFINET , 
Yes, there are managed packages like LeanData, CPQ, AdvancedApprovals, LinkedInSalesNavigator etc. that alter the Opportunity object.
I am trying to understand how I should interpret the results with this.

**Comment by VinceFINET** [comment]
@rangaraj 
OrgCheck is using the subtable called "Limits" on the "EntityDefinition" table from Tooling API.

The salesforce documentation is 
![image](https://user-images.githubusercontent.com/3799275/145412088-40a134a6-ee69-42e4-a2ed-b07408bb0f32.png)


Could you perform this query in (for example) Workbench to get the sub data from REST Explorer.

----

Go to the REST Explorer here:
![image](https://user-images.githubusercontent.com/3799275/145418160-bfb1c54b-d35f-4c80-a00b-be2cb0893391.png)

----

Then in the input text you put the following:
`/services/data/v53.0/tooling/query?q=SELECT+DurableId,+DeveloperName,+Description,+NamespacePrefix,+ExternalSharingModel,+InternalSharingModel,+(SELECT+DurableId,+Label,+Max,+Remaining,+Type+FROM+Limits)+FROM+EntityDefinition+WHERE+DeveloperName+=+'Opportunity'`
Like in this example
![image](https://user-images.githubusercontent.com/3799275/145418286-4c239839-d046-434c-9fd6-890123f4bae1.png)

----

You will get a visual result of the JSON structure
![image](https://user-images.githubusercontent.com/3799275/145418379-de389481-d8d5-4fe4-8af5-08b50bc09898.png)

----

But you can get the JSON file if you request the "RAW RESPONSE"

----




And go back to me with the results.

Thank you

**Comment by VinceFINET** [comment]
@rangaraj did you have the chance to perform the task?

**Comment by VinceFINET** [comment]
putting this issue in incubation since i cannot reproduce the error.

**Comment by VinceFINET** [comment]
in the first screenshot we see the limits were not the good ones, if they belong to Opportunity object they should start with Opportunity. Here we see some custom objects internal id.
So more likelely that code was confuses with two objects with the same label.
This has been solved in the current release.
I will close the ticket then
