### ISSUE TITLE
Download a tabular representation of dependencies

### ISSUE THREAD

**Issue by rangaraj** [SalesforceLabs/OrgCheck#124]
**Is your feature request related to a problem? Please describe.**
This is a request for an enhancement to get an export of artifacts(fields, classes etc.) and their dependencies presented.

**Describe the solution you'd like**
My customer would like a list of Fields and Dependencies in a tabular representation. A tree view is cumbersome when they have a large number of fields to cleanup today.

**Describe alternatives you've considered**
Still thinking, there is no alternative. Need to look at the code.

**Additional context**
[Sample Dependency graph for Opportunity_DealId_Status.html.pdf](https://github.com/VinceFINET/OrgCheck/files/7140953/Sample.Dependency.graph.for.Opportunity_DealId_Status.html.pdf)

Navigating this for every field takes a while.

**Comment by VinceFINET** [comment]
If you want a tabular representation of the dependencies, I believe it would be just like the underlining technical table called MetadataComponentDependency in the Tooling API.

But instead of showing the raw data in a table i would rather propose two tables. One for the references and one for the referencees.

Like in your example:

```
TargetName, Relation, Type, Name
Deal_Id_Status, is used by, ApexClass, QuoteExtControllerTests
Deal_Id_Status, is used by, ApexClass, BCS_TestData
Deal_Id_Status, is used by, ApexClass, QuoteTriggerHandler_Test
...
Deal_Id_Status, is used by, ApexTrigger, OpptyGetDealId
Deal_Id_Status, is used by, WaveDataflow, Maven_Dataflow_V2
...
Deal_Id_Status, is using, N/A, N/A
```

What do you think @rangaraj ??

**Comment by VinceFINET** [comment]
The dependencies will have two icons now.
Something like:
![image](https://user-images.githubusercontent.com/3799275/145626139-7ca92718-9a61-4522-8550-e49be77f055b.png)

One for the diagram view.
and the other for the tabular view.

**Comment by VinceFINET** [comment]
Having two icons was confusing after a second thoughts.
I keep one icon.
And put the table just below the diagram.

Example:
![image](https://user-images.githubusercontent.com/3799275/145822400-7ff2eb88-19be-431f-bb89-20abb1a34357.png)
