### ISSUE TITLE
Add a bad score when API will be soon retired

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#129]
Additionnaly to the 3 year old API (that gives a +1 on the score), I would like to have like a +3 if the API is going to be deprecated by Salesforce.
Please refer to that article for the list of APIs that Salesforce is going to deprecate: 
- https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/api_rest_eol.htm
- https://help.salesforce.com/s/articleView?id=000351312&language=en_US&mode=1&type=1
- https://help.salesforce.com/s/articleView?id=000354473&type=1

**Comment by VinceFINET** [comment]
as per our discussion on linkedin --> @nvuillam 
this is a feature i could have in OrgCheck

**Comment by VinceFINET** [comment]
@nvuillam i read in this article that the API number of Apex Classes is not to be concidered with the retirement of API versions....
I am confused myself.

Indeed the article mentions this:
_**This retirement does not include Custom Apex REST & SOAP Web Services, Apex Classes, Apex Triggers, or Visualforce Pages**_

So the impact is only on the integration part??
What is you hardis package is doing exactly???

Take care of yourself!

**Comment by nvuillam** [comment]
@VinceFINET > Yep, the impact is on external applications that calls standard SF API (not custom ones build with apex classes ^^ )

But that's a huge impact anyway ! :)

It's all explained here -> https://nicolas.vuillamy.fr/handle-salesforce-api-versions-deprecation-like-a-pro-335065f52238

And what **sfdx hardis:org:diagnose:legacyapi** does: download EventLogFile items and analyze them :)
