### ISSUE TITLE
Not all Flows are listed in the Flows sub-tab

### ISSUE THREAD

**Issue by cbcruz74** [SalesforceLabs/OrgCheck#130]
Hi, 

When I open the Flows sub-tab under the Automations tab, only a subset of the Flows is displayed. And all of those displayed were installed via a managed package.

To Reproduce
OrgCheck Information
Version: v1.9.5
Installed on OrgId: 00D3N0000000hsX

Thanks!

**Comment by VinceFINET** [comment]
Hi

so I see two things in this request.
1- you want to select the package of the list of flows diplayed in the page
2- you see that the list seems limited to (for example) the first 200 flows... and you d'ont get all of them.

Correct?

**Comment by cbcruz74** [comment]
I would like to see all Flows in the org, as well as their classification (score and comments). The package selection is of lesser importance. Sorting would be enough.

**Comment by VinceFINET** [comment]
And on your side Carlos you are telling me that you see 30 flows in OrgCheck but have 133 in reality...

**Comment by VinceFINET** [comment]
@cbcruz74 
Can you tell me how many records do you get when you perform the follwing queries with the Tooling API? 
`SELECT Id FROM Flow`
