### ISSUE TITLE
Object Documentation Export button doesn't work

### ISSUE THREAD

**Issue by pznddq** [SalesforceLabs/OrgCheck#131]
**Describe the bug**
The Object Documentation > Export button doesn't export a copy of the selected content.

**To Reproduce**

1. Navigate to the Objects tab
2. Select "No package" and any object (e.g. Account)
3. Click the Export button

**Comment by VinceFINET** [comment]
As a start, when you have the feature "export" on in a page, but user is on a tab that does not implement that feature you will have that message. Peevious you had no information.
![image](https://user-images.githubusercontent.com/3799275/145574628-c548e967-c72e-4a03-baec-04bd147d9f8e.png)

I know it does not answer yet your issue.

**Comment by VinceFINET** [comment]
That would be like this: 
![image](https://user-images.githubusercontent.com/3799275/145600421-ac27213e-2ba1-4147-9609-38efff6aa64d.png)
