### ISSUE TITLE
Sorting column "code coverage" on Apex screen does not work

### ISSUE THREAD

**Issue by iwerstler** [SalesforceLabs/OrgCheck#136]
**Describe the bug**
When trying to sort by code coverage, the table does not sort at all. 

**To Reproduce**
click on column header for code coverage

**Comment by VinceFINET** [comment]
Thank you for reporting this issue.
If it is blocking for you, I suggest you export the data as CSV file and do the sorting in Excel while i solve this issue.

**Comment by VinceFINET** [comment]
Good catch @iwerstler !! I just reproduced that error on my sandbox.

**Comment by VinceFINET** [comment]
There is an error in fact when the type of data is specically set to "numeric", the values that we compare are not the numeric ones but the string representations (as returned by the percentage decorator).
Very nice catch.
