### ISSUE TITLE
Error in Automation tab

### ISSUE THREAD

**Issue by lalconSFDC** [SalesforceLabs/OrgCheck#137]
OrgCheck Information
Version: v1.9.6
Installed on OrgId: 00D5r0000004hJF

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Operating System: MacIntel
Language: es-ES

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 1814
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '3012o000000UTS8AAO'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at h.getError (/resource/1640170168000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at /resource/1640170168000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (/resource/1640170168000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at /resource/1640170168000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (/resource/1640170168000/orgcheck__OrgCheck_JSForce_SR:4:9798)

**Comment by VinceFINET** [comment]
Thanks for this notification @LauraAlcon

**Comment by VinceFINET** [comment]
Duplicate for #74 
the error happens when requesting too many records in unitary requests. 
this can only be fixed by implementing a queue to avoid this to happen.
