### ISSUE TITLE
Add CumulusCI

### ISSUE THREAD

**Issue by Julian88Tex** [SalesforceLabs/OrgCheck#138]
Add CumulusCI to this project in order to simplify Dev/QA org creation: https://cumulusci.readthedocs.io/en/latest/

**Comment by VinceFINET** [comment]
@Julian88Tex 
Really great idea!!!!

Could you propose such a file? 
Or at least the _actions_ you would need?

**Comment by Julian88Tex** [comment]
Sure, this parge goes over the basic setup: https://cumulusci.readthedocs.io/en/latest/get_started.html

Did a quick and dirty PR after running `cci project init`: https://github.com/VinceFINET/OrgCheck/pull/139

**Comment by VinceFINET** [comment]
Check PR #174

**Comment by VinceFINET** [comment]
@Julian88Tex I discovered that having the cumulusCI created a scratch org at every commit is not such a good idea as it hits the limit of number of env to be created per day....

Maybe limit that to main branch?

**Comment by Julian88Tex** [comment]
@VinceFINET or perhaps just on merges. GitHub Actions can also be run manually: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
