### ISSUE TITLE
Unable to access the objects tab

### ISSUE THREAD

**Issue by dlralban** [SalesforceLabs/OrgCheck#144]
Salut Vincent, c'est Alban ;) ! J'ai l'erreur suivante  quand je clique sur la tabs Objects dans notre org chez mon client...

OrgCheck Information
Version: v1.9.6
Installed on OrgId: 00D1t000000Dmg4

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: INVALID_TYPE
When: While creating a promise to call "private_query".
What:
index: 0
queryMore: undefined
queryString: SELECT Id, SubscriberPackage.NamespacePrefix, SubscriberPackage.Name FROM InstalledSubscriberPackage
queryUseTooling: true
Stack:
INVALID_TYPE: sObject type 'InstalledSubscriberPackage' is not supported.
   at h.getError (/resource/1641486325000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at /resource/1641486325000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (/resource/1641486325000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at /resource/1641486325000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (/resource/1641486325000/orgcheck__OrgCheck_JSForce_SR:4:9798)

Object Documentation
Object Documentation
Object Configuration Overview

**Comment by VinceFINET** [comment]
The user running that page is not a system administrator right? but you assigned to that user the OrgCheck Permission set right ?

**Comment by dlralban** [comment]
Right, I'm not sys admin in Prod where it does not work, but it does work
in Sandboxes where I am Sys Admin

Le mar. 18 janv. 2022 à 15:24, Vincent FINET ***@***.***> a
écrit :

**Comment by VinceFINET** [comment]
Good catch!!! I was able to reproduce the error !!
With a simple user (not system admin) that has just the OrgCheck permission set.

![image](https://user-images.githubusercontent.com/3799275/149958273-7be2ac2e-0401-48d4-af18-8dfc5a38feb2.png)

**Comment by VinceFINET** [comment]
I found this article about this issue
https://salesforce.stackexchange.com/questions/282560/invalid-type-sobject-type-installedsubscriberpackage-is-not-supported

I will modify the permission set in the package
In the meantime you can modify the permission set your self with that permission enabled.

As I see it, this new system perm gives a lot of extra permissions, check that:
![image](https://user-images.githubusercontent.com/3799275/149971497-8db21a42-8181-4c06-95cb-efca3baff4a5.png)

But it works afterwords.
