### ISSUE TITLE
Missing "Export to CSV" buton in "Profiles and permissions" Tab

### ISSUE THREAD

**Issue by nvuillam** [SalesforceLabs/OrgCheck#15]
![image](https://user-images.githubusercontent.com/17500430/106119313-56b8d400-6155-11eb-990c-d4743bb6a58e.png)

**Comment by nvuillam** [comment]
+ same for RoleListing

**Comment by VinceFINET** [comment]
Yeah thank you to bring this to my attention. It was more due to a lack of time on my side. I will do this for 1.9

**Comment by nvuillam** [comment]
Thank you :)

**Comment by VinceFINET** [comment]
@nvuillam Worked on this issue today. 

Two things that need to be changed:
- the data available is the raw data that comes from the database and not the little plus that is shown on the page (for example the "badness score". I believe this needs to be changed because if you need an export, obviously you will want to have that extra information as well
- when the page has multiple types of data (and multiple tabs) like profile and permission sets, or groups and queues, which data do you want to export? both or only the one you see (so according to the currently opened tab?). if both then it's going to be challenging to have one CSV file and multiple data (columns are not the same etc...). 

What do you think?

**Comment by nvuillam** [comment]
@VinceFINET I used your tool as part of an audit performed for a client :)
And who says audit says reports ... so I was kind of frustrated to have to copy-paste in excel the nice data you provide :)
One CSV by visible page, undepending how it is organized as tabs, would be nice :)

**Comment by VinceFINET** [comment]
ok so need to refactor some things to:
- process once the data from the database and add the "magic" like badness score. have this data as a json.
- decorate that json as a datatable AND as an exportable file

If multiple data I could do something like this:
```
** Profiles **
Id, Name, Score, Custom, License, User Type, Package, Number of Users, Description
Xxxxxx, Custom: Sales Profile, 2, TRUE, Salesforce, Standard, , 0, 
Xxxxxx, Custom: Marketing Profile, 2, TRUE, Salesforce, Standard, , 0, 
...

** Permission Sets **
Id, Name, Score, Custom, License, Package, Number of Users, Description
Yyyyyy, OrgCheck_Users, 0, TRUE, Salesforce, OrgCheck, 1, OrgCheck Users
Yyyyyy, LightningOrderManagementAgent, 0, FALSE, Lightning Order Management User, force, 0, Read Access to all entities enabled by Order Management
...

** Login Hour Restrictions **
Profile, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
ABC, ...
XYZ, ...

** IP Range Restrictions **
Profile, Description, Starts, Ends
ABC, ...
XYZ, ...
```

**Comment by nvuillam** [comment]
Thanks :)
About multiple data... I think it would be best in separate files, to reduce manual refactoring effort to provide human readable reports :) ( and build summary pivot tables on excel haha )

**Comment by VinceFINET** [comment]
so if multiple files, I am thinking of two options:
1. keep the current button that will generate a zip file (is it even possible in javascript?)
2. keep the current button that will pop-up a little menu to select which file you want to generate (in case there is only one file to generate, obviously no menu!!)
3. have multiple buttons for each file on the "action" zone on the top right ??

Option 2 or Option 3 ??

**Comment by nvuillam** [comment]
4. Only one button, who generates CSV for the currently viewed tab ? :)

**Comment by VinceFINET** [comment]
in this fourth scenario, do you think a different label for the button would help the users understand that behavior

**Comment by VinceFINET** [comment]
I could do option 4. 
I have the possibility to show a button only when selecting a specific tab.
So I could use this to have multiple "export" buttons but only one would be visible at the same time...

**Comment by nvuillam** [comment]
I think you think too much :)
One button, exporting the content of the currently displayed tab, and that's all :)

**Comment by VinceFINET** [comment]
On my way to make the option 4 for all tabs!! ;)
