### ISSUE TITLE
Help understand scoring system

### ISSUE THREAD

**Issue by josegarciaponce** [SalesforceLabs/OrgCheck#153]
**Is your feature request related to a problem?**
 No

**Describe the solution you'd like**
It would be great if every tab described what is considering as "bad" to create a bad score. Even just a description under each tab on what will be "judged" by the tool would help a lot, otherwise you have to figure out why is consider something bad, which can be obvious for some components but not for others.

**Describe alternatives you've considered**
A description

**Comment by VinceFINET** [comment]
Great ! I have a lot of feedback about the score computation. And clearly the current « question mark » button is not natural and easy to use lot of you. 

I really need to take some space in the page to show part of what is currently shown in the question mark modal. 

Without taking too much space from the content of the page!

**Comment by VinceFINET** [comment]
First I will add a hover simple text on the "stop" icon in the "Score" column, explaining what needs to be checked:
![image](https://user-images.githubusercontent.com/3799275/151987494-6bc29e3e-bc37-4944-b3cb-7be91fb33778.png)

**Comment by VinceFINET** [comment]
For example:
![image](https://user-images.githubusercontent.com/3799275/152002260-160e39c4-d96e-4fb0-b866-fb007ebd3eef.png)

or:
![image](https://user-images.githubusercontent.com/3799275/152002318-9d4fbd53-6dfc-4b63-852a-dd3ec17d0df4.png)
