### ISSUE TITLE
Apex description page should include buttons/icons fr greater clarity

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#165]
**Describe the solution you'd like**
In the description of the page, when you mention an icon or a button it would be much clear for the user to include the icon of the button itself inside the description... for the like button and the plug button

**Comment by jstukas** [comment]
👍  Is this hard to do ?

**Comment by VinceFINET** [comment]
not at all.
I 'm just logging this to make sure it is done in the next release!

**Comment by VinceFINET** [comment]
Instead of using the icon, i highligh the icon with the same "yellowis" warning color, like here:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3799275/178039213-23876d54-a7fe-43af-84bb-4f4ab3df0816.png">

I think that is enough for the user to understand...
