### ISSUE TITLE
Error #0: EXCEEDED_ID_LIMIT

### ISSUE THREAD

**Issue by edmund888chan** [SalesforceLabs/OrgCheck#173]
OrgCheck Information
Version: v1.9.7
Installed on OrgId: 00D020000004eXU
Current running UserId: 005G0000001vtoGIAQ

Navigation Information
Page: /apex/OrgCheck_CustomFields_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Operating System: MacIntel
Language: en-US

Error #0: EXCEEDED_ID_LIMIT
When: While creating a promise to call "private_query".
What:
index: 0
queryMore: undefined
queryString: SELECT DurableId, DeveloperName, IsCustomSetting, QualifiedApiName, NamespacePrefix FROM EntityDefinition WHERE DurableId LIKE '01I%' AND (NOT DurableId LIKE '%.%')
queryUseTooling: true
Stack:
EXCEEDED_ID_LIMIT: EntityDefinition does not support queryMore(), use LIMIT to restrict the results to a single batch
   at r.getError (/resource/1644509729000/orgcheck__OrgCheck_JSForce_SR:1:72641)
   at /resource/1644509729000/orgcheck__OrgCheck_JSForce_SR:1:71009
   at /resource/1644509729000/orgcheck__OrgCheck_JSForce_SR:1:229622
   at /resource/1644509729000/orgcheck__OrgCheck_JSForce_SR:1:229650
   at MutationObserver.o (/resource/1644509729000/orgcheck__OrgCheck_JSForce_SR:1:104504)

**Comment by VinceFINET** [comment]
Issue on the data store called « customObjects »

**Comment by VinceFINET** [comment]
Linked to issue #123
