### ISSUE TITLE
Profiles/Permissions tab resulting in an error

### ISSUE THREAD

**Issue by danvyle** [SalesforceLabs/OrgCheck#176]
The other tabs pull information correctly, but am having issues with the Profile and Permission sets tab. I've created API enabled permission set and confirmed that I have the orgCheck permission set assigned. Can you help us look into this? I suspected a static resource error so saved several jQuery static resource files which still has not resolved the error.

Here is the error I'm receiving: 
Error #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'id')
   at Object.onEnd (/resource/1650934055000/orgcheck__OrgCheck_OrgCheck_SR:3613:65)
   at /resource/1650934055000/orgcheck__OrgCheck_OrgCheck_SR:1756:38
   at /resource/1650934055000/orgcheck__OrgCheck_OrgCheck_SR:245:25

**Comment by VinceFINET** [comment]
Hi @danvyle 

Thank you for logging an issue here.

From the stacktrace, I think the error is related to the code below:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/3799275/165268681-a79d375d-bfa3-4845-b26e-30cf8645c847.png">

But it seems wrong as the error:
`Cannot read properties of undefined (reading 'id')`
... is referencing the property 'id' and not "Id" (with capital "i")

Is it an error that you have during the loading page ? or the error is not even captured by the OrgCheck error dialog box at all?

Maybe we could arrange a screen share together for me to better understand the issue.

**Comment by VinceFINET** [comment]
Can you execute the below query (using the regular REST API, not the Tooling API):
```
SELECT Id, AssigneeId, Assignee.ProfileId, PermissionSetId 
FROM PermissionSetAssignment
WHERE Assignee.IsActive = TRUE
AND PermissionSet.IsOwnedByProfile = FALSE
```

And send me the output?
Thank you

**Comment by danvyle** [comment]
Hi Vincent,

Happy to do a screen share if this can resolve our issue. Let me know when
you have availability today, I can work around it. Attached is a csv of the
output from the query. I also linked a screenshot to show you the other
parts of the error if it might help. It seems like it hits the error during
the mapping stage of retrieval. Let me know what you think!

The error pops up as the page is loading,


Dan-Vy

**Comment by VinceFINET** [comment]
Awesome screen share! thanks for your time.
We identified the error.
I will correct it in the next release.

If someone has the issue @danvyle will give you in some moments the patch that we did to correct the issue.
As the package is an unlocked package you can edit the file in your org in the meantime.

:D

**Comment by danvyle** [comment]
Thank you @VinceFINET again for your time today! 

The fix was in editing the static resource file: "Org_check_Orgcheck_SR.js" around line 3613. Here is what we added:

for (const [key, value] of Object.entries(psgByName1)) {
//code to add start--
            if(psgByName2[key]){
                                value.groupId = psgByName2[key].id;
                                value.description = psgByName2[key].description;
                                value.isUndescribedCustom = value.isCustom && !value.description;
                                psMap[value.id] = value;
                                }
//-- code to add end
                            };

Hope this helps anyone else running into the same issue!

**Comment by VinceFINET** [comment]
Implement the correction in code for next version!
