### ISSUE TITLE
CRUD Comparisons on Permission Sets & Fields

### ISSUE THREAD

**Issue by cdgeorg17** [SalesforceLabs/OrgCheck#178]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The beta feature to show CRUD OBEJCT access comparisons between Profiles, which is wonderful!  Even more helpful would be FIELD CRUD access comparisons on Profiles **and** Permission Sets

**Describe alternatives you've considered**
N/A

**Additional context**
Salesforce is recommending we move away from Profiles & instead add field and object access at the Permission Set level.  My recommendation would speed up that conversion tremendously.

**Comment by VinceFINET** [comment]
Thank you for this request. 
in terms of UX what is the most relevant for you?

1- Select an object then a field to see the CRUD of this field for all profile and existing ps
2- Select a profile or ps to see the CRUD of all fields for this existing profile or ps
3- other??

**Comment by cdgeorg17** [comment]
Hello, good question and thanks for reading my suggestion so quickly!

#3 - If possible, select object & have all fields listed out in rows.
Common permission sets & profiles listed out in columns (or Vice versa).

To explain, we’re trying to build as few permissions sets as possible when
converting our profile’s field access to permissions. The wholistic view
would be a lot faster than selecting individual fields.

Let me know if you have additional questions.

Thank you!

Cassie

**Comment by cdgeorg17** [comment]
I want to add… this will return a lot of data/rows/columns.

I would suggest showing an example (first 20 fields & profiles/permission
sets) & allow the user to export the rest to excel.

That way we can do our own data analysis & play around with what we want to
display and compare.

I’m open to suggestions, that’s just what came to mind first.

Thanks!

Cassie

**Comment by VinceFINET** [comment]
This idea has been split into multiple tickets:
- #107 give info about CRUDs on Profile/Permission Set
- #108 give info about FLSs on Profile/Permission Set
- #109 give info about Apps on Profile/Permission Set
- #94 give info about Password Policies on Profile/Permission Set

I will close this ticket.
You can follow the corresponding tickets.
Thank you
