### ISSUE TITLE
Make OrgCheck not usable if run from a Production org which is not a Trial nor a Demo org

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#182]
To avoid reaching the API limit in your production org (just in case), i would like to make OrgCheck unusable from a production org.

OrgCheck should not be usable if the current org has: 
- STATUS = Active
- TYPE = Production

OrgCheck should be usable in all other cases.

Maybe I could have a "ByPass" checkbox saying that you accept to run OrgCheck in your production org or something similar...

**Comment by nvuillam** [comment]
I think OrgCheck is best suited for 10 years old orgs full of **** ... and usually most of them don't have a sandbox full, or it is not refreshed yet ^^
Maybe add a PS to make sure to provide access only to people knowing what they are doing ?
Or even better: check for API limits before running OrgCheck requests ? ^^

**Comment by VinceFINET** [comment]
the permission set is already there, but you could run the app when you are System Admin.

**Comment by VinceFINET** [comment]
So the limits to check first should be for sure:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/3799275/177527727-e37d2e48-03da-4487-a943-57f7a172dd10.png">

And maybe only this one as a start...

**Comment by VinceFINET** [comment]
Then I should check the endpoint: /services/data/v55.0/limits
And in the JSON response filter for the property called "DailyApiRequests"

Example is:
"DailyApiRequests": {
        "Max": 15000,
        "Remaining": 14987
    },

maybe in addition of the global checkbox....

**Comment by VinceFINET** [comment]
This should be based on the result of the SOQL:
```
SELECT IsSandbox, OrganizationType, TrialExpirationDate 
FROM Organization 
```

In a sandbox (the edition could change of course) you would have:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/3799275/177977439-bddf803f-6e2b-46b6-89c8-0f9822706e16.png">

In a Dev Edition org you would have:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/3799275/177977491-dff6c5a6-6bca-4b3e-927c-cd7743b8bf68.png">

In a Trial org I suspect the expiration date will not be null/empty

In a production org (the edition could change of course) you could have:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/3799275/177977653-8da3ffa8-769e-4261-9236-960a5c5726a0.png">



As a conclusion, the citeria should be:
- `OrganizationType = 'Developer Edition' ` --> if current org is a DE
- `OR IsSandbox = true` --> if current org is a sandbox
- `OR (IsSandbox = false AND TrialExpirationDate <> null )` --> if current org is a trail demo

**Comment by VinceFINET** [comment]
Some changes in the code, but the query "SELECT IsSandbox, OrganizationType, TrialExpirationDate FROM Organization" is async and result is not yet ready when rendering the page.... need to find a better way to have this fullfill.
