### ISSUE TITLE
Error Received Running Profile & Perm Sets

### ISSUE THREAD

**Issue by deanrose** [SalesforceLabs/OrgCheck#188]
OrgCheck Information
Version: v1.9.7
Installed on OrgId: 00D8Z000001t6ef
Current running UserId: 0058Z000008663bQAA

Navigation Information
Page: /apex/OrgCheck_ProfilesPermSets_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Operating System: MacIntel
Language: en-US

Error #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'id')
   at Object.onEnd (/resource/1658175526000/orgcheck__OrgCheck_OrgCheck_SR:3613:65)
   at /resource/1658175526000/orgcheck__OrgCheck_OrgCheck_SR:1756:38
   at /resource/1658175526000/orgcheck__OrgCheck_OrgCheck_SR:245:25

**Comment by cidarm** [comment]
Hi - I am getting the similar error via Chrome:

```

OrgCheck Information
Version: v1.9.7
Installed on OrgId: 00D56000000MSle
Current running UserId: 00556000009KxsOAAS

Navigation Information
Page: /apex/OrgCheck_ProfilesPermSets_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Operating System: MacIntel
Language: en-US

Error #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'id')
   at Object.onEnd (/resource/1659127929000/orgcheck__OrgCheck_OrgCheck_SR:3613:65)
   at /resource/1659127929000/orgcheck__OrgCheck_OrgCheck_SR:1756:38
   at /resource/1659127929000/orgcheck__OrgCheck_OrgCheck_SR:245:25

```

**Comment by VinceFINET** [comment]
Line 3613 is here in the PermissionSet Assignment datastore:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/3799275/182249440-d5260612-7d16-415a-ae63-9751b0c9a156.png">

As i am preparing the next version of OrgCheck, will it be possible for you to work with me beta testing the new verion and check if you have still this issue with the new version?

**Comment by VinceFINET** [comment]
After a little investigation this is already resolve in the next future version.
please see #176

**Comment by VinceFINET** [comment]
@deanrose @cidarm is this issue finally resolved when you upgrade to the newest version of the package via https://sfdc.co/OrgCheck-InstallToday ???
