### ISSUE TITLE
Add a filter on the table view

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#19]
Is it possible to add filter in table view in order to filter on name of fields or apex ... ?

**Comment by VinceFINET** [comment]
There are a lot of table libraries in javascript. I used **_handsontable_** previously. Check for example the list of potential table framework to use or to be inspired from: https://bashooka.com/coding/javascript-data-table-libraries/

**Comment by jalal3107** [comment]
Very useful
