### ISSUE TITLE
Error to display the Object Documentation for Asset Object

### ISSUE THREAD

**Issue by jihanemess2022** [SalesforceLabs/OrgCheck#197]
**Describe the bug**
The Object Documentation doesn't display correctly for Asset Object. Please see the error attached

**To Reproduce**
1- Click on Object Documentation
2- Filter on No Package
3- Select Asset Object
![image](https://user-images.githubusercontent.com/113693048/190637741-30d0adca-a74f-4797-8eaa-1e708df71246.png)

**Comment by VinceFINET** [comment]
So it's working on my testing environment.
I see the error here is on the "Using" cell.
Could you paste the "What" section here? and send me this by email?

**Comment by jihanemess2022** [comment]
Please go here <https://github.com/VinceFINET/OrgCheck/issues> and log an
issue with the following information.

Salesforce Information
Salesforce API Version: 55
Installed on OrgId: 00D9E0000009oIp
Type of this org: Sandbox
Current running UserId: 0057T000000RcPoQAK
Current Daily Api Requests: {"Max":5000000,"Remaining":4999626}

Navigation Information
Page: /apex/OrgCheck_Objects_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US

Issue #0: TypeError
When: Datatable: calling formula to render the content of a cell in the
table
What:

   - Column: Using
   - Formula: (r) => { if (r.custom === true) { const count =
   helper.html.render.whatIsItUsing(r.id, object.fieldDependencies[r.id]);
   if (count > 0) return helper.html.render.checkbox(true) + ' ' + count;
   return helper.html.render.checkbox(false); } }
   - Property: undefined
   - Data: {"aggregatable":true,"aiPredictionField":false,"autoNumber":false,"byteLength":0,"calculated":false,"calculatedFormula":null,"cascadeDelete":false,"caseSensitive":false,"compoundFieldName":null,"controllerName":null,"createable":true,"custom":true,"defaultValue":null,"defaultValueFormula":null,"defaultedOnCreate":false,"dependentPicklist":false,"deprecatedAndHidden":false,"digits":0,"displayLocationInDecimal":false,"encrypted":false,"externalId":false,"extraTypeInfo":null,"filterable":true,"filteredLookupInfo":null,"formulaTreatNullNumberAsZero":false,"groupable":false,"highScaleNumber":false,"htmlFormatted":false,"idLookup":false,"inlineHelpText":null,"label":"Available
   for
   Withdrawal","length":0,"mask":null,"maskType":null,"name":"vlocity_ins__AmountAvailableForWithdrawal__c","nameField":false,"namePointing":false,"nillable":true,"permissionable":true,"picklistValues":[],"polymorphicForeignKey":false,"precision":18,"queryByDistance":false,"referenceTargetField":null,"referenceTo":[],"relationshipName":null,"relationshipOrder":null,"restrictedDelete":false,"restrictedPicklist":false,"scale":2,"searchPrefilterable":false,"soapType":"xsd:double","sortable":true,"type":"currency","unique":false,"updateable":true,"writeRequiresMasterRead":false}

Stack:
TypeError: Cannot read properties of undefined (reading 'undefined')
   at Object.formula
(/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r9E000000CCfQ&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m9E000000Bg9hQAC&nonce=43e0ea72f76c31e467598780df7397c712359782fea2b8ec9fe47d71b9644320&sfdcIFrameOrigin=/>
  at
/resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:78364
   at Array.forEach ()
   at /resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77745
   at Array.forEach ()
   at DatatableHandler.create
(/resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:77486)
   at Object.create
(/resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:10880)
   at
/apex/OrgCheck_Objects_VFP?sfdc.tabName=01r9E000000CCfQ&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m9E000000Bg9hQAC&nonce=43e0ea72f76c31e467598780df7397c712359782fea2b8ec9fe47d71b9644320&sfdcIFrameOrigin=/>
  at
Object.end
(/resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:8623)
   at AbstractProcess.fire
(/resource/1661872721000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:56877)

ExportExport the content of this box...


Le ven. 16 sept. 2022 à 15:10, Vincent FINET ***@***.***> a
écrit :

**Comment by VinceFINET** [comment]
i understand this field has no "id" property and the code is not checking for that condition.

**Comment by VinceFINET** [comment]
so i will change the code to check if the id property exists.
Marvelous!

**Comment by VinceFINET** [comment]
dear @jihanemess2022 

Could you perform the following **SOQL** in your org, please?
```
SELECT Id, DurableId, QualifiedApiName, DeveloperName, Label, NamespacePrefix 
FROM FieldDefinition 
WHERE EntityDefinitionId = 'Asset'
AND DeveloperName = 'AmountAvailableForWithdrawal'
AND NamespacePrefix = 'vlocity_ins'
```

And also on **workbench / REST Explorer**, execute the following action:
```
/services/data/v54.0/sobjects/Asset/describe
```
And, on the response, unfold the section "fields" then "vlocity_ins__AmountAvailableForWithdrawal__c'


Normally the "`QualifiedApiName`" in the first query SHOULD match the "`name`" in the second request.
We can setup a call if you like.

**Comment by VinceFINET** [comment]
in fact, the "`id`" is a property that OrgCheck is adding from the standard "`describe`" method.
The reason is that the **Dependency API** relies on this id and not on the name of the field...

**Comment by VinceFINET** [comment]
Ok so i reproduced the error in my dev org.

Question: if you perform the following query with Tooling API does it returns zero or more than one record???
```
SELECT Id, DurableId, DeveloperName, QualifiedApiName,  Description, IsIdEnabled, PublisherId, NamespacePrefix, IsCustomSetting, DetailUrl, EditDefinitionUrl, EditUrl, HelpSettingPageUrl, NewUrl
FROM EntityDefinition
WHERE DeveloperName = 'Asset'
```

In my case, it returns two records, one for a Standard SObject and one for a Custom Metadata Type that I created with the same name.

**Comment by VinceFINET** [comment]
note to myself: using `DeveloperName` is really a bad idea. the code should use `QualifiedApiName` instead, which seems more 'unique'.

**Comment by VinceFINET** [comment]
@jihanemess2022 

What happens if you run the following query (using Tooling API)?

```
SELECT Id, DurableId, DeveloperName, QualifiedApiName,  Description, IsIdEnabled, PublisherId, NamespacePrefix, IsCustomSetting, DetailUrl, EditDefinitionUrl, EditUrl, HelpSettingPageUrl, NewUrl
FROM EntityDefinition
WHERE DeveloperName='Asset'
AND PublisherId IN ('System', '<Local>')
```
