### ISSUE TITLE
Custom Fields incorrectly listed as not used

### ISSUE THREAD

**Issue by annacrotty** [SalesforceLabs/OrgCheck#198]
Perhaps I'm misunderstanding "not used," but I've got a number of custom fields that are populated for most records that are showing up as "not used." I do think this category (custom fields that aren't in use) is super useful for this, but it doesn't seem to be providing useful information in my org.

Thank you so much for making OrgCheck - I am enjoying using it and am excited that it exists.

**Comment by VinceFINET** [comment]
Hi @annacrotty 

"Not used" means the field is not referenced by any other component in your salesforce environment.
At least that the Dependence API is listing (for instance it does not include the Workflow Field Update)
But it would include if the field is mentioned in an Apex class, or include in a Page Layout for example.

It's more about configuration and setting than the data itself.
A field can be empty or full of values in millions of records.
But if that field is not referenced anywhere that means the value it contains is useless to your users and your company and maybe you would need to delete it from your data model.

**Comment by VinceFINET** [comment]
but i can understand that the expression "not used" might be misleading.
what would you prefer, we can discuss a more comprehensive expression that "speaks" to anyone...

**Comment by VinceFINET** [comment]
What about this?

Instead of the current wording:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3799275/197528722-ee2dcf2d-022e-43e9-a572-8ad40cf0c2e4.png">

I put the following:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/3799275/197529411-5d3f728c-6019-4e36-8842-5f0c3d66244c.png">
