### ISSUE TITLE
Error on Custom Fields tab

### ISSUE THREAD

**Issue by manjunath-ghub** [SalesforceLabs/OrgCheck#201]
I have installed orgcheck in a sandbox successfully. But when I try to go to Custom Fields tab, the app is throwing an error after 2-3 mins of processing. Below is the screenshot I see for this error. Please reach out to me if you need additional details:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/69909024/194900329-53cfafb6-76d6-4dda-9ef1-76b8dc4fbb2a.png">

**Comment by VinceFINET** [comment]
Dear @manjunath-ghub 

Did you try the actions listed here: 
https://support.google.com/chrome/answer/95669?hl=en&co=GENIE.Platform%3DDesktop

Thank you.

**Comment by manjunath-ghub** [comment]
Hi @VinceFINET ,
I tried clearing browser cache and clicked on 'Custom Fields' Tab again. Now I get this error:

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/69909024/195159063-27af14d3-0199-430b-964e-89c317db79e1.png">

**Comment by manjunath-ghub** [comment]
@VinceFINET , any update for me here? Can you please provide me a build with 201 and 202 fixes?

**Comment by VinceFINET** [comment]
Hi @manjunath-ghub 

could you provide the entire logs including the error stack?

also could you tell me what's the result of the query (with the Tooling API):
```
SELECT COUNT(Id) 
FROM CustomField
WHERE ManageableState = 'unmanaged'
```

**Comment by VinceFINET** [comment]
Merging this ticket with #224
