### ISSUE TITLE
Error on Batches tab

### ISSUE THREAD

**Issue by manjunath-ghub** [SalesforceLabs/OrgCheck#202]
I have installed the app in a Sandbox.

When I click on Batches tab in the app, I get an error. Please see the screen below for error details. I will be happy to share additional details if needed. Appreciate if you can prioritize this issue to address.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/69909024/194901378-df5913aa-6894-432a-918a-39c19099b529.png">

**Comment by VinceFINET** [comment]
The bug appears when one of the records in the following query (listing uncomplete batches in your org) has no CronJobDetail for some reasons:
```
SELECT CreatedById, CreatedDate, CronExpression, CronJobDetailId, CronJobDetail.JobType, CronJobDetail.Name, 
      EndTime, Id, LastModifiedById, NextFireTime, OwnerId, PreviousFireTime, StartTime, State, TimesTriggered, 
      TimeZoneSidKey 
FROM CronTrigger 
WHERE State <> 'COMPLETE' 
LIMIT 10000

```

The code that raise this error is the following:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/3799275/195018452-3c072df2-3973-48cf-9c54-bd41959238a3.png">

Following modification will resolve the issue: 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3799275/195018706-39d4666a-a349-4704-9c9c-9d66d77b316d.png">

**Comment by VinceFINET** [comment]
'?' notation is to be prefered.

Like here:
```
let jobTypeLabel = 'XXX'; 
const r = {}; 
switch (r.CronJobDetail?.JobType) {
      case '1': jobTypeLabel = 'Data Export'; break;
      case 'A': jobTypeLabel = 'Reporting Notification'; break;
}; 
let jobName = r.CronJobDetail?.Name || 'YYY';
console.debug(jobTypeLabel, jobName);
```

The output is:
```
XXX YYY
```
