### ISSUE TITLE
Accessing Automations tab returns error

### ISSUE THREAD

**Issue by rameshkali** [SalesforceLabs/OrgCheck#216]
Accessing the Automations tab takes a long time and returns  an error

**To Reproduce**
Access the Automation tab
![Error2](https://user-images.githubusercontent.com/67335869/205205006-7241a6d6-7ec7-4278-8a06-40a1e6025c96.png)
![Error](https://user-images.githubusercontent.com/67335869/205205008-d72e71a5-1b82-4f8c-af0a-e389f51b286f.png)

**Comment by VinceFINET** [comment]
@rameshkali in this org what does return the SOQL with Tooling API: `SELECT COUNT(Id) FROM Flow`

**Comment by VinceFINET** [comment]
I would need to understand how can we select less flows in your case....

**Comment by rameshkali** [comment]
SOQL returns *2080. *Thanks!

**Comment by VinceFINET** [comment]
in my dev end I have 2288 flows and it's working fine. 
what version are you using?
the one from appexchange?
on the home page "Hydrogen H,1" is mentioned??

**Comment by VinceFINET** [comment]
Merging this ticket with #224
