### ISSUE TITLE
I suggest to augment the width of the Score column of the Custom Fields tabs

### ISSUE THREAD

**Issue by jmsfez** [SalesforceLabs/OrgCheck#219]
**Describe the bug**
The width of the Score column of the Custom Fields tabs is too narrow

**To Reproduce**
Copy and past the information from the error dialog box here!!

**Comment by VinceFINET** [comment]
Hi @jmsfez 

In the current version (Hydrogen), the column score looks like nothing i do agree.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/3799275/208107000-ab6e5009-41e9-4d59-b560-b8f0fd22496f.png">

The next version (Helium) will bring "sticky headers in the table.
And i believe that at the same time i corrected the issue you mentioned.
look at this example:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/3799275/208107208-a082fec8-2e61-4e26-99f5-e7a118b0bdfa.png">

**Comment by VinceFINET** [comment]
#158 is the ticket I was mentioning.
It solves your issue in the next version.

I will then closed this ticket as it will be resolved for you when you have the next version.

THANK YOU!
