### ISSUE TITLE
No access to the Profiles and Permission Sets tab

### ISSUE THREAD

**Issue by dlralban** [SalesforceLabs/OrgCheck#223]
**Describe the bug**

Hello Vincent, bonne année 2023 et encore bravo pour orgCheck !

I'm trying to access the "Profiles and permission sets" tab of orgCheck in my dev org, but it throws me an error message (see below).

Note : I'm a System Admin, I've cleared the cache before and after the following steps and I've just removed all perm sets except some Trailhead permission sets and the Key Manager pset (I had tested Salesforce shield in this org a while ago) which contains the "Manage Encryption keys" permission. In order to make sure this is not Shield related, I've disabled field encryption and file encryption, so that Shield no longer applies in my org, but I'd rather not play with the Key Manager permission in this dev org (which is my historical dev org!), as I'd like to keep access!... Maybe this has nothing to deal with Shield, but I prefer to warn!

Thanks for your help and time and Happy new year!

Alban

**To Reproduce**

When clicking on Profiles and permission sets of orgCheck, it stops during the process 

Dataset [profiles]: ended successfuly
Dataset [permissionSets]: ended with an error
Dataset [permissionSetAssignments]: ended successfuly
Mapping process ended with an error
Records: initialize...
Actions: initialize...

... And throws me the following error message.

Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 00D24000000r53K
Type of this org: Developer Edition
Current running UserId: 00524000001E17cAAC
Current Daily Api Requests: undefined

Navigation Information
Page: /apex/OrgCheck_ProfilesPermSets_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: fr-FR

Issue #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'records')
   at /resource/1662018423000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:57930
   at Array.forEach ()
   at /resource/1662018423000/orgcheck__OrgCheck_SR/js/orgcheck.js:1:57898

**Comment by VinceFINET** [comment]
Merci bonne année à toi également !

Ton bug m'a permis de tester une extension dans VS Code pour aller directement à la bonne ligne et colonne dans le fichier orgcheck.js  --> https://marketplace.visualstudio.com/items?itemName=davidfreer.go-to-character-position
Comme le fichier javascript "orgcheck.js" est généré automatiquement sur une ligne... pas facile de voir ou l'erreur se trouve avec la stack !! Pour info l'extension est top !!

The error is located on the code OrgCheck.Salesforce.js file:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/3799275/210337281-41fec405-c540-4d16-89b2-a3353791c65f.png">

`result.records` seems to be `undefined` in your case for the dataset "permissionSets".
Indeed in the code i dont check if the records property is defined or not.

Can you tell me in your org what is the result of this SOQL query (using REST, not tooling api) ?
```
SELECT COUNT(Id) FROM PermissionSet WHERE IsOwnedByProfile = FALSE
````

Thank you !!!

**Comment by dlralban** [comment]
Merci de ton retour rapide ;) !

ça fait 5, soit tous mes permission sets :

<img width="769" alt="image" src="https://user-images.githubusercontent.com/40574902/210339869-ee815daa-6a04-4400-9550-3689839d2a1a.png">

**Comment by VinceFINET** [comment]
and if you type this SOQL does it give you an INVALID TYPE or a nice result?
```
SELECT COUNT(Id) FROM PermissionSetGroup
```

**Comment by dlralban** [comment]
I have the following error message :

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/40574902/210342744-5697d32f-c540-4193-8def-ee9aa131b51e.png">

**Comment by dlralban** [comment]
Permission Set Groups are not available in this old dev org... That's probably the reason. I've checked the release updates and found no mention to Pset groups, then checked the documentation and it says I should have the "Manage Profiles and Permission Sets" permission, which is the case. I'll open a Case at Salesforce, but here is my orgId if you want to investigate yourself: 00D24000000r53K (I've just authorized Salesforce and orgcheck support if needed ;) !). Again, thanks for your time, I'll keep you updated if I find a fix

**Comment by VinceFINET** [comment]
no no don't anything.... that just helps me to find the origin of your issue.
and to reproduce it!

**Comment by VinceFINET** [comment]
i also have a DE with no PSgroup feature so hopefully i can reproduce the error on my side.
but having the checking in the code i just added earlier should do the trick anyway...

**Comment by VinceFINET** [comment]
Bim just reproduced it!!
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3799275/210350604-76efa2c7-d20f-4095-8c5b-27749bfe26ca.png">

**Comment by VinceFINET** [comment]
Stay tune for Helium!!!

**Comment by dlralban** [comment]
Thanks Vincent ! In addition, Salesforce support just told me I had to create another dev org, because they could not enable the feature in dev orgs that were created before '20... Therefore, I will create another dev org to solve this issue (...and other ones that would probably happen if I continue using the current one).
