### ISSUE TITLE
Show only the permissions that are *set* (turned on) in a Permission Set

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceLabs/OrgCheck#226]
**Is your feature request related to a problem? Please describe.**
Often when I inherit someone else's implementation, I am faced with 
1) No documentation (it may have been created but is now lost)
2) No descriptions in Setup (lazy devs and poor project oversight)
3) A list of custom permission sets with no way of knowing what they do

I want to see what individual permissions have been set in each permission set, all on one page.

As it stands now, you need to manually open each Permission Set and click through each main navigation link to see what is on that page.  For example, you click the Object Settings then look through the resulting list for anything that is not "no access" or "-".  Then click Assigned Apps, Assigned Connected Apps, etc, etc ad nauseum to see what items may have been added.  This is a nightmare!

Note that when you make changes to a permission set, the system automatically displays a summary of what you've done.  I want a similar summary to be available on demand.  

**Describe the solution you'd like**
OrgCheck would be the ideal place to show this.  In my view, when you are looking at the permission set list, clicking on the permission set should drill down into what items are set in that permission set (rather than the current behaviour that takes you to the permission set in Setup).  On that page would be sections for each of the major navigation items in the permission set definition (Assigned Apps, Assigned Connected Apps, Object Settings, etc), with the section hidden if there are no settings in that section for that permission set.

**Describe alternatives you've considered**
AppExchange: User Access and Permissions Assistant
AppExchange: Org Security Centre (Metazoa)

**Additional context**
-- none --

**Comment by VinceFINET** [comment]
@charles-thompson-salesforce-com 

I started to look at your request.
A good start I believe would be to have the number of FLS and CRUD permissions on the table (as a total whatever the object/field).
For example like this:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/3799275/222293120-da6fe735-4d75-40ca-a9b0-967ef5ce82aa.png">

What do you think ??

And yeah after that I could have a dialog box when clicking on the permset link to show FLSs and CRUDs.

**Comment by charles-thompson-salesforce-com** [comment]
Great start!
The Object Settings page on the Permission Set UI is not too bad - on the
one page it gives a good idea of the CRED settings for each of the objects,
although it would be better if it just showed the objects that are not
blank.

I think of more importance would be the System Permissions info, listing
only the permissions that are set -- maybe a semicolon-separated list like
a multiselect picklist.

**Comment by VinceFINET** [comment]
Should it be aligned with the four main permissions like in the User tab:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/3799275/222295171-abe954a5-54d6-4052-870f-c426b19d1ed4.png">

All of them may be overwhelming in the table i am afraid...
Plus the system perm on PSET is not a subtable it's a list of fields that may change in time.... that's horrible to query !

**Comment by charles-thompson-salesforce-com** [comment]
Right!  Understood.  Thanks for taking on this challenge!
