### ISSUE TITLE
Remove or decrease the width of Description in Custom fields

### ISSUE THREAD

**Issue by manjunath-ghub** [SalesforceLabs/OrgCheck#231]
**Describe the bug**
The Description column is too wide, takes up lot of real estate on the page. Due to this other critical pieces of information like Dependency, Usage etc. are at the far right and we have scroll horizontally to see these values. When you scroll and move to this information you no longer see the which field and object the data belongs. Can you please improve this experience. 

**To Reproduce**
Copy and past the information from the error dialog box here!!

**Comment by VinceFINET** [comment]
I proposed in #230 to shrink the description to up to 50 characters as a start.
But i understand that maybe the right thing to do would be to simply move the description columns as far to the right as it could be....
Would it be good for you?
