### ISSUE TITLE
Profiles & Permissions Error

### ISSUE THREAD

**Issue by sarahkhalid2** [SalesforceLabs/OrgCheck#241]
**Describe the bug**
When you go to the Profiles & Permissions tab the page stays stuck when running background analysis. It gets stuck at this particular step:
In particular when running Dataset [profilePasswordPolicies]: starting... 

**To Reproduce**
Install OrgCheck in an org and then go to the Profiles & Permissions tab, it will not load

**Comment by VinceFINET** [comment]
Duplicate #239
