### ISSUE TITLE
Undefined error : "Oh no, Org Check had an error!"

### ISSUE THREAD

**Issue by celliautou** [SalesforceLabs/OrgCheck#256]
After clicking on the "Plug" button in "Apex class and triggers"/"Recompilation needed" tab : I got an undefined error : "Oh no, Org Check had an error!"

Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D5E000000BXrE
Type of this org: Sandbox
Current running UserId: 0057S0000016GWZQA2
Current Daily Api Requests: {"Max":5000000,"Remaining":4999768}

Navigation Information
Page: /apex/OrgCheck_ApexComponents_VFP

System Information
Language: fr-FR

Issue #0: undefined

**Comment by VinceFINET** [comment]
what a misery! the technical description (given by the tool itself) of the error is quite poor.
so to better understand what's wrong, please tell me a little bit of context.
you are on the apex page obvisouly, ok...
- which subtab?
- how many apex classes needs recompilation in your case?

:D Merci !

**Comment by celliautou** [comment]
Yes, Apex classes tab. 109 classes to be recompiled.
![image](https://user-images.githubusercontent.com/72150000/226417171-546a70ed-6cc1-4036-bd63-7d8508a31638.png)

**Comment by VinceFINET** [comment]
A fix has been done to limit to 25 the compilation order.
you had 109, and the composite api is limited to 25 max.

This is a quick fix but of course I should split in multiple batch instead of limiting you to 25.
I will do this in Beryllium.
