### ISSUE TITLE
flows are flagged as "inactive flow" though the flow is active

### ISSUE THREAD

**Issue by celliautou** [SalesforceLabs/OrgCheck#257]
**Describe the bug**
In the "Custom Field" tab it appears that almost all the fields used in flows are flagged as "inactive flow" though the flow is active. 
Even for a flow with only 1 version, the field "referenced in inactive flows" is checked.

**To Reproduce**
[CustomFields.csv](https://github.com/SalesforceLabs/OrgCheck/files/11018676/CustomFields.csv)
for ex see NORAM_Opportunity_Event__e referenced in 
![image](https://user-images.githubusercontent.com/72150000/226353656-55590db8-80ce-4c4d-bfdf-6ef2051f61fe.png)

**Comment by VinceFINET** [comment]
could you copy a screenshot of the dependency tree for field Opportunity.Cancellation_date
this one has (i am refering to your csv export) 4 references : 2 layouts, 2 flows (including 1 inactive).
Thank you

**Comment by celliautou** [comment]
Here it is
![image](https://user-images.githubusercontent.com/72150000/226414481-b70b6784-9860-4718-92b0-48a63ada13d0.png)

**Comment by VinceFINET** [comment]
Hello

it seems the flow has two versions:
![Image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/df64f348-2691-4d5d-a67b-6ecfa4d59477)

One is active and the other is not active.

Maybe cache in orgcheck was invalid.
What happens if you remove all cache from the Org Check Home page (including the cache called "Flows")

Does it show again in the dependencies ??

**Comment by VinceFINET** [comment]
before pushing the new minor version of Beryllium need to work on this one.

**Comment by VinceFINET** [comment]
I removed the active or inactive detection for flows.
So now if a custom field is used in a flow version active or inactive it will be viewed as used even thought these versions of the flows are active or not.

another way to put it would be to say why only focusing on Flows you could have custom fields used in a validation rules that can be deactivate also....
