### ISSUE TITLE
Profile and Perm Set issue

### ISSUE THREAD

**Issue by rspecks1** [SalesforceLabs/OrgCheck#267]
**Describe the bug**
Installed OrgCheck for Admins only, opened up profile and perm sets tab, let it run, came back to look at it 45 mins later and had the below error

**To Reproduce**
Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D8K0000002KNQ
Type of this org: Sandbox
Current running UserId: 0051N000006bL3FQAU
Current Daily Api Requests: {"Max":38610000,"Remaining":38609325}

Navigation Information
Page: /apex/OrgCheck_ProfilesPermSets_VFP

System Information
Language: en-US

Issue #0: ERROR_HTTP_400
When: While creating a promise to call a SOQL query.
What:
index: 0
queryMore: undefined
queryString: SELECT Id, Name, Description, IsCustom, License.Name, NamespacePrefix, Type, CreatedDate, LastModifiedDate, (SELECT Id FROM Assignments WHERE Assignee.IsActive = TRUE LIMIT 1), (SELECT Id FROM FieldPerms LIMIT 101), (SELECT Id FROM ObjectPerms LIMIT 101)FROM PermissionSet WHERE IsOwnedByProfile = FALSE
queryUseTooling: undefined
Stack:
ERROR_HTTP_400: Access Declined
   at r.getError (/resource/1683125510000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1683125510000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1683125510000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229622
   at /resource/1683125510000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229650
   at MutationObserver.o (/resource/1683125510000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)

**Comment by VinceFINET** [comment]
Hello

Thank you for logging this issue.

If you run the following SOQL what is the result?
`
SELECT COUNT(Id) FROM PermissionSet WHERE IsOwnedByProfile = FALSE
`

Maybe the issue is with the sub queries. Even if I limit them, maybe would be intelligent to not have 101 as limit but 21 ???

**Comment by rspecks1** [comment]
Hi!

Thank you for the quick response. I'm getting 182.

Thanks,

**Comment by rspecks1** [comment]
Hi, 

Just wondering if there's any update on this or anything I can try to resolve this? 

Thanks for the help

**Comment by rspecks1** [comment]
Hi Vince, 

Appreciate assistance on this and don't mean to "bug" (pun intended), but are there are updates or anything I can do from my end to assist? 

Thanks.
