### ISSUE TITLE
installing in a Enterprise Edition org that has 30 custom tabs and whenever I attempt to install I am getting the error :

### ISSUE THREAD

**Issue by donaldrivard** [SalesforceLabs/OrgCheck#269]
**Describe the bug**
installing in a Enterprise Edition org that has 30 custom tabs and whenever I attempt to install I am getting the error :

**To Reproduce**
Install on an org 30+ tabs

**Comment by VinceFINET** [comment]
Thank you for this alert.
can you ask support to increase the limit of your org...^^ just kidding.

i believe i should reduce the number of custom tab i am using in short term.
how many custom tab do you have left in this org?

in long term i am planning to change the UI and use LWC components with one page application approach instead. that will solve your problem for sure, but not gonna happen fast i am afraid.

**Comment by VinceFINET** [comment]
Refactoring the UI to avoid having so many custom tabs in the package

**Comment by VinceFINET** [comment]
Let's close this ticket, the new version with LWC will indeed not require anymore custom tabs in your org.
