### ISSUE TITLE
I'm in production now - is there a way to stop the error message from coming up that says that I need to uncheck the check box?

### ISSUE THREAD

**Issue by bhare1357** [SalesforceLabs/OrgCheck#275]
**Describe the bug**

**To Reproduce**
Copy and past the information from the error dialog box here!!

**Comment by bhare1357** [comment]
Salesforce Information
Salesforce API Version: 57
Installed on OrgId: 00D70000000Mbiz
Type of this org: Production
Current running UserId: 0054u000006oUAtAAM
Current Daily Api Requests: {"apiUsage":{"used":71918,"limit":5098400}}

Issue #0: Error
When: We stopped here because of our Watch Dog Guard! Waouf!
What:
level: ERROR
message: Your org is a Production Org. To bypass this warning, uncheck the security option.
type: OrgTypeProd
data: {"orgType":"Production","orgId":"00D70000000MbizEAC","orgName":"Fidelity Investments"}

thisis the error message I'm referring to

**Comment by VinceFINET** [comment]
The option is located on the Homepage!

**Comment by bhare1357** [comment]
Right - but right now when I open prod and go to the org check app - that error comes up before I can uncheck the check box - so was wondering if there was a way to keep it unchecked once we accessed the app the first time - or something like that? :) - thanks

**Comment by VinceFINET** [comment]
so right now if you go to the app, select Home
<img width="323" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/9921a54d-9e79-424c-a43b-7194661b3257">

you will then have the error 
<img width="462" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/7031ac73-1e86-4c06-8fc4-3ba5e9c9f2ae">

either type "Escape" key or close the dialog where you have the error (the X on top right)

then you will have access to the setup:
<img width="899" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/926dd023-4ce0-48dd-80b5-29c8325b7c52">

uncheck the option
<img width="232" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/32b96413-92f7-4b9f-8b17-a110512f65bf">

and then
<img width="213" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/20d5dbdc-eed2-4456-83d8-a7f26d8c06ff">

go back to the other tabs you have no warning again.

**Comment by VinceFINET** [comment]
ok so maybe I should have a more userfriendly way to turn this on and off....

Two things:

**first** on the home page there is no reason why I should raise that error.... 
i should switch the dialog off on the home page.

**second**  in the dialog box the sentence should be more explicit like "go to the home page (maybe a link as well) and look for this option to turn it off"

**Comment by VinceFINET** [comment]
@bhare1357  do you have your issue solved?
