### ISSUE TITLE
Add the Data Classifcation fields

### ISSUE THREAD

**Issue by macalmon** [SalesforceLabs/OrgCheck#276]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
In the Object Documentation report it would be great to have the Data Classification fields of 
- Data Owner
- Field Usage
- Data Sensitivity level
- Compliance Categorization

This way at a glance I can see what fields need my attention to go tag properly

**Describe alternatives you've considered**
Going in one by one to check or find another 3rd party app

**Additional context**
![image](https://github.com/SalesforceLabs/OrgCheck/assets/31143160/9eb1afdc-d1f7-4d38-87a4-382354b2cb84)

**Comment by VinceFINET** [comment]
i like this idea VERY much !!

So here you want the information on the Object tab in the fields section.
Will it make sense also to have this information on the Custom tab as well??

**Comment by VinceFINET** [comment]
for information: https://help.salesforce.com/s/articleView?id=sf.data_classification_metadata_fields.htm&type=5

**Comment by VinceFINET** [comment]
will be available in the next version !! thank you for this idea !!



![Image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/a45880eb-2680-4839-85f3-b09fec72bd30)

**Comment by VinceFINET** [comment]
with values 

![Image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/373baf33-d27b-4acb-91be-515159f449a5)

**Comment by VinceFINET** [comment]
I will not implement this on the custom tab page as it requires potentially more time to display the page for some orgs.
