### ISSUE TITLE
"Analytics Home" (winter 23) vs 🤪 Analytics tab in OrgCheck

### ISSUE THREAD

**Issue by ghost** [SalesforceLabs/OrgCheck#278]
I don't know if this is something on my end.  

From the Salesforce Help doc "[Find Your Reports and Dashboards Faster in Analytics Home](https://help.salesforce.com/s/articleView?id=release-notes.rn_rd_reports_browse.htm&release=240&type=5)":

1. From Setup, in the Quick Find box, enter reports, and then select Reports and Dashboards Settings. 
2. Select Enable the Unified Experience for Analytics Home. _[I confirmed this is checked]_
3. From the App Launcher, select Analytics. _[The only option for me is the Analytics tab for OrgCheck.]_

Am I missing something?

Thank you!

**Comment by VinceFINET** [comment]
the article is not specifying if your user must have a special system permission to view this Analytics Home tab.
I am almost certain that there is something we are missing here in terms of permission / profile assignment for your user.

First, if you uninstall Org Check from this org, do you have access to the Analytics Home tab that you targeted? Or you have no analytics tab anymore (which i suspect).

Second of course re-install Org Check in this org ! and check if you have like System Profile, and system permission called "see all reports and dashboard" or "see all analytics". I honestly don't know what are the pre-requisite for this feature.

**Comment by ghost** [comment]
Hi Vincent - Thank you for the follow-up.

I will uninstall Org Check shortly, but I wanted to share another wrinkle first.

Last week, while poking around something else, I noticed that a report I looked at had a slightly different header (the actual webpage).  I copied the URL and then removed the reference to the actual report ID and found myself at the main analytics tab.  I bookmarked the URL so I could get back to it (https://medecisionsf.lightning.force.com/lightning/page/analytics).

**Comment by ghost** [comment]
I have uninstalled Org Check.  You are correct, I am still not able to find the "Analytics" tab in the App Launcher.  But the URL that I had saved still works.  Reinstalling now.

**Comment by ghost** [comment]
no change after reinstalling - still not able to access analytics home tab from App Switcher.

**Comment by VinceFINET** [comment]
so it seems not linked to orgcheck. the next version will be less intrusive as i revmoed the custom tabs.. :D

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
UPDATE - Hi Vincent - just wanted to let you know that there was a disconnect between the keyboard and the desk chair that was causing this issue.  Apparently, someone (cough, me) didn't realize that the permission set "CRM Analytics Platform Admin" was needed in order to have access to the Analytics tab (aka Analytics Studio).

So mystery solved!

Thanks again for providing a really helpful (and awesome) tool!

**Comment by VinceFINET** [comment]
This is nice to finally see a logical solution for this issue.
:D
