### ISSUE TITLE
Access to Org Check via Permission Set

### ISSUE THREAD

**Issue by dylan-guest** [SalesforceLabs/OrgCheck#281]
**Is your feature request related to a problem? Please describe the solution you'd like**
As a Salesforce Administrator, I want to be able to give access to Org Check to other leaders in our Salesforce org space through a permission set, so they have the ability to use the tool from a documentation perspective when doing analysis for feature development.

**Describe alternatives you've considered**
All users isn't feasible based on API usage being impacted. I would say it isn't an extremely large concern if this was the path we took, but Principles of Least Privilege regarding the information you can see with Org Check is necessary. A permission set seems to be the best path forward based on eventual sunsetting of profiles being heavily used for access to certain areas within Salesforce.

**Additional context**
Happy to discuss in comments or hear from others that have encountered this issue and resolved in another way.

**Comment by VinceFINET** [comment]
Hi @dylan-guest !

Unfortunately I can't have such permission set in the package.
Right now the use of the app requires to have modify all. which in turns add automatically all CRUDs on all objects in the permission set.

I tried this before and realized that such permission set (containing a reference to all my objects) could be not compatible with your org....

i tried several solutions including altering the permission set before pushing in the repo and the package....
none worked.

the only solution i had is to install the app for system admins.
sorry about this situation if it is not giving you satisfaction.
