### ISSUE TITLE
Users tab - additional column

### ISSUE THREAD

**Issue by pritaunk** [SalesforceLabs/OrgCheck#29]
On the users tab, an additional column that shows which users some of the significant sys admin permissions (when users have multiple permission sets assigned), this column will help identify where something has been provisioned in error. I can see the **Key permissions** column, but don't think it currently flags that the user has access to export all data.

**Comment by VinceFINET** [comment]
At this time we are checking the following permissions: apiEnabled, viewSetup, modifyAllData, viewAllData.
i know there was a bug about this info but can't find the issue in the tracker.

**Comment by VinceFINET** [comment]
When testing 1.9 current in beta I have the following screen on User tab, will it be ok for you??
![image](https://user-images.githubusercontent.com/3799275/107495035-d7cd8d80-6b8f-11eb-9aff-bd5eea7a5e7a.png)

**Comment by VinceFINET** [comment]
For some reason in the current version that you have permission are always empty! this will be fixed in 1.9!

**Comment by pritaunk** [comment]
Yeah, i thought it was my sandbox so i had to refresh/logout login to see the permissions. 
Additional permissions to check could be:

- Export Reports
- Manage Connected Apps
- Manage Multi-Factor Authentication in User Interface
- Manage Package Licenses
- Manage Release Updates
- Modify Metadata Through Metadata API Functions
- Weekly Data Export

All of these permissions under **Manage users**  are deemed high risk for orgs under SOX scope (compliance) where these permissions are usually limited to specific users only.

![image](https://user-images.githubusercontent.com/31191979/107574697-e1ceab00-6be6-11eb-9160-bcb9056731ae.png)
