### ISSUE TITLE
Additional info on Classes/Triggers Overview tab

### ISSUE THREAD

**Issue by pritaunk** [SalesforceLabs/OrgCheck#32]
1. An additional column on the **triggers** overview tab would help if it flags which triggers have logic added (as we know logic should be within classes, not the trigger itself!)

2. On the apex **classes** overview tab - an additional column that flags if there are SOQL Queries/DML inside FOR Loops -> not sure if it's possible to go to this level of detail though?

**Comment by VinceFINET** [comment]
The two requirements are very interesting but needs to analyse Apex code...
PMD should be better at this. Check ApexPMD at https://pmd.github.io/latest/pmd_apex_metrics_index.html

We could probably check some quick stuff like size of a trigger should not be for example more than 500 characters? if it is the case, we might suspect that there is logic in it.... 
What would be the threshold in terms of size for a trigger??

**Comment by pritaunk** [comment]
thanks @VinceFINET ! will check out  ApexPMD, is it similar to what CodeScan does?

re: We could probably check some quick stuff like size of a trigger should not be for example more than 500 characters? --> let me go through some of the triggers in my org (we have loads of triggers) and come back to you with an avg # on characters i see.

**Comment by VinceFINET** [comment]
Any update @pritaunk ?

**Comment by pritaunk** [comment]
Should have this info by end of week, does it need to be character count or # lines do? 
So far I am seeing triggers without logic can go up to roughly 20-25 lines (600-650 characters, without space) @VinceFINET

**Comment by pritaunk** [comment]
Just noticed one **WITH** logic that goes up to 7500 characters and 165 lines!!!!!!! 
@VinceFINET

**Comment by VinceFINET** [comment]
ok so adding a warning if triggers have more than 5000 characters
