### ISSUE TITLE
Incorrect Flagging of DML Statement with body of 'CustomChangeEventTrigger' Apex Trigger

### ISSUE THREAD

**Issue by TechMaverick41** [SalesforceLabs/OrgCheck#337]
**Describe the Issue:**
The Org check tool incorrectly identifies a DML statement within the body of the "CustomChangeEventTrigger" apex trigger. Upon careful examination, it appears that the tool may have flagged the issue inaccurately.

**Details:**
Trigger Name: CustomChangeEventTrigger
Incorrectly Flagged: The tool reports a DML statement within the trigger body.
Reason for Discrepancy: While the DML statements are executed through methods (CustomEventServiceHelper.deleteCustomOutlookEvent and CustomEventServiceHelper.updateCustomOutlookEvent), they are not directly written within the trigger body. The trigger indirectly triggers DML operations through these helper methods.

**To Reproduce:**
`trigger CustomChangeEventTrigger on EventChangeEvent (after insert) {
    List<String> deletedIds = new List<String>();
    List<String> updatedIds = new List<String>();
    
    for (EventChangeEvent event : Trigger.new) {
        EventBus.ChangeEventHeader header = event.ChangeEventHeader;
        String changeType = header.changetype;
        List<String> changedFields = header.changedfields;
        List<String> recordIds = header.getRecordIds();

        switch on changeType {
            when 'DELETE', 'GAP_DELETE' {
                deletedIds.addAll(recordIds);
            }
            when 'UPDATE', 'GAP_UPDATE' {
                updatedIds.addAll(recordIds);
            }
        }
    }

    if (!deletedIds.isEmpty()) {
        CustomEventServiceHelper.deleteCustomOutlookEvent(deletedIds);
    }

    if (!updatedIds.isEmpty()) {
        CustomEventServiceHelper.updateCustomOutlookEvent(updatedIds);
    }
  }`

**Comment by VinceFINET** [comment]
Hello

The flag "Has DML" for trigger uses the following RegEx against the source code of the apex trigger:
`const REGEX_HASDML = new RegExp("(?:insert|update|delete)\\s*(?:\\w+|\\(|\\[)");`

In your example, the source code matches at index 75, at "deletedIds"
Which is of course wrong.

I will change the RegEx to make your example work properly.

**Comment by VinceFINET** [comment]
The RegEx should be:
`new RegExp("(?:insert|update|delete)\\s*(?:\\s\\w+|\\(|\\[)")`
