### ISSUE TITLE
Apex Recompile Failure

### ISSUE THREAD

**Issue by mlregal** [SalesforceLabs/OrgCheck#348]
Salesforce Information
Salesforce API Version: 59
Installed on OrgId: 00DE2000002bJov
Type of this org: Sandbox
Current running UserId: 005PE0000001AzpYAE
Current Daily Api Requests: {"apiUsage":{"used":2205,"limit":11868600}}

Navigation Information
Page: /apex/OrgCheck_ApexComponents_VFP

System Information
Language: en-US

Issue #0: undefined

**Comment by VinceFINET** [comment]
dear @mlregal, thank you for this ticket.
i guess it happens when you click on the button to recompile the classes that are listed in the corresponding tab?
how many classes do you have in this list?
do your current user in salesforce has the "Apex creator" system permission?

**Comment by VinceFINET** [comment]
This is fixed (hopefully) on Beryllium!
