### ISSUE TITLE
Beryllium - Beta Test - Issue with the global access of the app (after new version was pushed by Vincent to multiple test orgs)

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#361]
**Describe the bug**
Can't access the app after it's been pushed by Vincent to Subscribers that had Lithium previously.

**To Reproduce**
Subscriber has previous version of OrgCheck (from Unocked package or AppExchange -- same error)
Vincent push the Beryllium version (4.1) to some subscribers.
The install is successful.
But when user want to open the Org Check app, they have this screen:
![image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/6eefd013-5b66-4847-8e28-67aabf6b1533)
![image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/92338968-159e-4026-9a9a-cec18aeecfb7)

**Comment by VinceFINET** [comment]
The package contains a new Custom Tab that includes the app.
The previous Custom Tabs were removed from the package...

When checking the admin profile, this new Custom Tab has "tab hidden" property set.
![image](https://github.com/SalesforceLabs/OrgCheck/assets/3799275/9ba53641-0010-4c87-9279-b089965e18bd)

Workaround is to update the profile (or any permission set the user may have) and set this property to another value, and save.

**Comment by VinceFINET** [comment]
Need to find a solution for this, i am not going to ask all the user to do this workaround !

**Comment by VinceFINET** [comment]
In the package I will add an In-App Guidance Prompt
<img width="435" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/14bb3a0b-8767-42a3-8d1e-44bd3ba6e810">

In case you have this error you need to assign your user a new permission set I also include in the package.

**Comment by mweintraub-locala** [comment]
When it was installed for me today i also could not view the tabs so I had to enable them from lightning app builder

![Screenshot 2024-03-19 095409](https://github.com/SalesforceLabs/OrgCheck/assets/157053566/dd6f0648-4c03-4ba6-a752-6e4848107a91)

<img width="877" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/157053566/d898a5a8-be6e-4d8b-bc22-23b24869ff41">
