### ISSUE TITLE
Beryllium - Beta - Custom Labels Not included With Package and Have to Add Tabs to App Manually

### ISSUE THREAD

**Issue by mweintraub-locala** [SalesforceLabs/OrgCheck#364]
**Describe the bug**

- I am an admin user and was able to see org check app from the app launcher. 
- When I clicked it it took me to the app but there were no tabs. 
- I assigned myself the org check permission set but was still unable to see the relevant app tabs. 
- I went to lightning app manager and edited the navigation items to show the tab components relevant to this app -> which allowed the tabs to show on org check. 
- When I click into a given tab however (such as "Objects") it says the relevant custom label is missing. This is true for all tabs I tried. 
- I checked my custom labels from setup and don't see them. I also check the components from package details and do not see them. 

Relevant Screenshots

initial view after install and assigning relevant org check permission set:

![Screenshot 2024-03-19 095409](https://github.com/SalesforceLabs/OrgCheck/assets/157053566/85d34d44-fd0c-4183-9280-a0b80028a65d)

Enabling the tabs to show from lightning app manager:

![Screenshot 2024-03-19 095932](https://github.com/SalesforceLabs/OrgCheck/assets/157053566/31c1f0b9-d5fe-458f-ae12-97b6e8b7bce1)

After enabling tabs from lightning app manager and clicking into one of them:

![Screenshot 2024-03-19 100253](https://github.com/SalesforceLabs/OrgCheck/assets/157053566/7fbb507a-2975-41c5-9edc-edaa6105233b)

**Comment by VinceFINET** [comment]
OK i see the issue.
When i push an upgrade, previous components that i deleted from the package stays in the org. I have a ticket internally with AppExchange team.
Could you try to:
- add your user in the permission set "Org Check Users"
- access the app via the URL .../lightning/n/orgcheck__OrgCheck_App_TAB

**Comment by mweintraub-locala** [comment]
Via the URL provided I initially see the following under most tabs:

![Screenshot 2024-03-19 114359](https://github.com/SalesforceLabs/OrgCheck/assets/157053566/484a5984-2b37-45ec-baa2-74721823c7bd)

I clear metadata cache and can now see records under objects and custom field sub-tabs but still no data under any other sub-tabs (such as apex pictured in the screenshot above). I also cannot see batches or analytics sub-tabs within the app "home" tab. (I also tried the refresh button the list view under apex and other sub-tabs, no luck).

**Comment by VinceFINET** [comment]
I see you have a lot of classes in this org, most of them are NOT VALID (so need recompilation it seems)...
could you check if the sub tabs on the right of "Classes" (such as the sub tab called "Recompilation needed") have content in them?

Could you run the following query (and maybe send the result in PM in slack):
```
SELECT Id, Name, ApiVersion, NamespacePrefix, Body, LengthWithoutComments, 
     SymbolTable, CreatedDate, LastModifiedDate 
FROM ApexClass 
WHERE ManageableState IN ('installedEditable', 'unmanaged')
```

I removed the tabs batches and analytics in this version. 
notice that you have a "schedulable" sub-tab in this "apex" tab
what does it look like ??

Thank you

**Comment by mweintraub-locala** [comment]
actually seeing a bunch of the classes now

Sent you the results of the query via slack

seeing some schedulable classes under the sub-tab

**Comment by VinceFINET** [comment]
maybe i need to check for the cache of the previous and the new versions to not mess with each others....

**Comment by VinceFINET** [comment]
Previous version was using Visual Force page so the cache was directly the one from the browser.
Keys were like "`OrgCheck.Metadata.Objects`"

The new version is using LWC.
I see a generic key like `LSSIndex:LOCAL{"namespace":"orgcheck"}` that indicates the keys and their index.
And after that keys are just indexes....

I propose to have a "clean phase" in the main visual force page, in javascript, to make sure the previous cache is not wasting space in users browser.

**Comment by VinceFINET** [comment]
done
