### ISSUE TITLE
Watch dog stopped you here

### ISSUE THREAD

**Issue by LouiseRAUX** [SalesforceLabs/OrgCheck#365]
Hello,
I've just installed the package in production but I've this error message each time I try to use Org Check "

Issue #0:Error 

**When** : We stopped you here because of our Watch Dog Guard ! Waouf !

**What**:
Level : ERROR
Message : Your org is a Production Org. To bypass this warning, uncheck the security option.
Type : OrgTypeProd

Does anyone know what "uncheck the security option" means and how can I do this?
Thanks a lot !

**Comment by VinceFINET** [comment]
Hi @LouiseRAUX!

Thank you for using Org Check and raising an issue.

Let me show you:
<img width="1022" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/cc29cb65-16bf-4fdd-b992-68f45c67b287">

**Comment by VinceFINET** [comment]
Uncheck this option and then you can use the app in production.
