### ISSUE TITLE
Org check failed recomplie apex classes on "batch tab"

### ISSUE THREAD

**Issue by jumpaloo** [SalesforceLabs/OrgCheck#366]
**Describe the bug**
i clicked the recompile all classes (411) on batch tab and immediately the issue appeared

**To Reproduce**
Copy and past the information from the error dialog box here!!
Please go [here](https://github.com/SalesforceLabs/OrgCheck/issues) and log an issue with the following information.

Salesforce Information
Salesforce API Version: 60
Installed on OrgId: 00DKN0000008aJK
Type of this org: Sandbox
Current running UserId: 00524000001r17JAAQ
Current Daily Api Requests: {"apiUsage":{"used":184811,"limit":32100000}}

Navigation Information
Page: /apex/OrgCheck_Batches_VFP

System Information
Language: en-US

Issue #0: undefined

Issue #1: undefined

**Comment by VinceFINET** [comment]
Thanks for your ticket.
The new version Beryllium is going to resolve that issue.
It is going to be available on the AppExchange very very soon!

**Comment by jumpaloo** [comment]
great news, thanks

**Comment by jumpaloo** [comment]
as it seems to be a known issue -i will close this case.
