### ISSUE TITLE
OrgCheck Failed to install in my Customer's Sandbox

### ISSUE THREAD

**Issue by vaumont** [SalesforceLabs/OrgCheck#38]
We did not receive an email.
Here are the details from Splunk:

`from_index_sandbox(cs18)` 00D1100000C4RLa earliest=-10h logRecordType=pkgvt
| table _time userId operationType isSuccessful detailMessage isManaged isReleased packageName packageNamespace apId orgEdition orgStatus installSrc

![image](https://user-images.githubusercontent.com/58858217/109921332-91d88680-7c70-11eb-91d1-9a68b02801a5.png)

**Comment by vaumont** [comment]
Encrypted stack trace:

A-202103-ou2Kai8gR86ROUxVmGq4f9wlGnDY6W_caBFmW-fQ2rGYkUJ2ZQcTmANSP8H-yDxttovNyZthXWcDf7-Gregya05zE9Ont3DNR5hwj0mri6MZ_efy2U9P2dSlztk100PlRPL3FSAdSPOIgGSMdXBOhZ3KzaAKlxJJXimyUBQS9ukM9qda23z1zJkB0axZ3IZI8OBTyhrDuMI-OoLPi1C7yr8alZ2ttmC3DHVKBx9ShWIkoETdwqBSBASRSwBhZxiD5k_Efb6JtZWLtQDzOjbu2sdbGu_MfUgctF4Ih4UYWhWi3sxb_u1zL_ZPqI4JQ8ss-JYBhME-J7xvPh6arTl_IrobFDNvOrdaUoTI-5CPPllp4-9FtxndZMdguZuitsfw5sDA-o6X8lkkiKGLOvRY2hBbrS1y8k_VtM97d6Kse45cf4WsILMz_aace1qktfqpfqDgj3JtKLcmPndVkgXqVbjkw3z7jhp68njeTSLEE3Tj_00ELKak-Mk-37CI_ly0ttP7OALA-BHK7jfwr10rzSNe8AAz5r0rpkUvatc3BTXOGa1gyWnSIv1llmF9YSR48N6Lvz1kNOmFljO8SP1dwtWxkdlZV2v3xbqGjNH-fkTytSMAIUNcN4h7FR1Nak2hy6EUCZ7wb0SN7UclowCkdPhJsrfl7jAtFU5AwjkIIOA-MKPb8FtIg_Ra5Uvfd8f0mb3BCEEjlVPlRSis4S6aiO3KqbQhiA0D7QHAxd4ROEje9_csc2L7lgAxI-bjILBgt3_usEpqYbLeMrHnJEoE74Q3pvantwVRXdFcek0wRJZUfLugbYm1APjmSmWSmZ1q0fTghXgTBcVfI5AmoJYayKNX4SjhA5SM7ArbK4sPqeCOKwoPijTpkRnGbMmyJ5Ify6O3RYynK3SbjVK2vOqLiN8_G_Aw-b2vHmzfJbzglrLGzdpR0Z5ISs_W1nUZnx0l4kbxo3rEyZ78zaBdvWKvqmZrU_uVLnfbVQ4VpjdyoUQnHwz3yNSX31i6BskPMwdTfhHGa2iCyYcxhldOlbEzRB8g5L9ucEzychGnyIHtz5wEGMHSrKW686PzDFre90_bsGRZdopGQi91Xecz5EBM1K-xwSFHc3TesNgEorrPPVRkCvnP_Eosk4CQ_ZGnk7FDYPFtVZ7LKTGewKrAHmmsb1_WUB7L29OCw8O92Nhm8KWFM5IDoyIMi_whZnHnJN2p9fHK4jjzcAOUH9TXgCLH_3zIsvsqx5ifjW7U5SLB3ebTr1pmrfpRYVctycS8-sBUtXSBYQIBKjJsCSWHdOgQPu9BXeJLytaO-MJNntRaSgWmRzpTpH_l_DE0WmZ-eRCaL0SZfciZD2XYsZ6fXN7QHcxC52pzBeAmYqv_K_1nDXsM8y0NzzPUbeYLF1jr9HE5JwzbSbafCvJI6s6Ahqq7FeTKoqXI9KRxrzp8ydSdYohpGGFQBOcdhA4gwq2Kh1Z0Xk5k2UW2HGO4btxW25lmslPYqj3IPz-3fUEYwPEN4PYFyW4nqtg-aF288LKio2lMu4QWPd81oJiqJCUnXDx-0LVe6yhWNxVcLkdTTo8lAv7CV57yq5PVkDjrJZq2DBJ3DCFX4v11GpUlYfw09___SimCVJmrsuxeT_JVsUbudZP54DTAmYuG1cZ_rhvEmrJpSQIU0J8ZSsUKav4Sh3JsNsVLk2XQbLtYFT81o4wVLOzYvvxe26WFvx4tbq4EZSwsqMnVENSNMXVRMQwJSzcpk3yWY8IpaqkyuGT89cvikCDEIr3YEIbi9TCBNNt8yfwIshTlwpYBuOJHxMkFwn4x3gb5EjI9g8g8utVxC1uLTF24X75wII__gd4KBeRjeAaV2TzX1JBfkmmpU0bTOcgIpCfIm02YgbX3SiNL8bWj7_B8KX4sTlyp6keQOyTpxAqS7X-H8ICGh7XTx5zjN--w7PqwjnHPK8xV4hl5rcHmmIgk7FqKRIjRMTB8XiRYaxJYqX_wmNu196YgBzv7lCgvJpqBiNXgpA9G2vfcfZYEBhI1GhxxqwDxryEtRs_Jgs7QIIR2yxu19ntPr7aF2i8z_-Af3suGfmS1iTWeasVoHqJOayl7SBGuekQ7P3DIPcv-IBg7GGcO3y2fQabqA1eYb_Ywkw1Na-tI9ji4241RFyKzYdgp2RC50Fr0lx0sEa47oOguxot_YM9KddJLH-tCpBZwfU7WHABIQSmCb6FfsgTZ_GDscmy-RDzi9mvicQ6Iv_bo8ssYTF_1zf_M_-NpCEVsznkhfTy6a7AIb8wyaAG_pL-ZU1Qnu7Ptqd79SRjzI3ULfYbyxezRZkFm-RdUMUKkAITcmHkxAXvjW1Zt91gba22y31-Vxft_39_HDjTPNcW3YxB_UL37LSqGY9A0TuJiaLIJav_R6-kXCsciQBdB0U9InxuO7l29KKT-8aAAcKPQPKxim1W5Frn8r-G3nWM4ETT78L7BusFhfuDrE2x_8f9S4-OyaBcu_tTs6tcIzcZl2z2bVFjzgtjXbvtxu7X3ycn2zLkCsXou2FYwnsStaGI_BqFyhSjj3vRX8qDdWPluXdGMlTElgzXlJ_2SB59r4bW9X7_zo65pZ_FX6EhsLJQyXpRFVI00c6jJCJkgWzPP6x2bqgO6RpGePZB1bm8hqSL4TYJWaFranQTf_o_TR5Pz9LDexYy7ZY2XNByYwk7S4m0L4-J2uzdAJ6vPO_Hq8t42Iwt84mheTbzCRiKupwpgmkP3oCQrSf_E1tLJPNw9Z99ijTLhiYwqOBti2_vddWcL5TRUdGRrIJIKvv2smR0OY-TDTmKzCYPE3SAsxoMmVTpOXWeFcvDjUOaSkIEJS7k7bEcKOl9Dp9CoZqdwYtA8_-NtDgrmk_48gDeuoAFAwaPrftHYckb-KwlrrBcNlqrobAxSO3Jktrbz60C807238RkQQ5nN64OqZZhy00yeLE4c6Sx-bq7wP5y2Up4BpHoTlnvaItZgZARSt4sku5Jx3IkT9308eiNkSoV6tGA1rQndFuu4c6lecZ22M8aqfyBX6966bPYhAAXIedL3TDtLszskwpTrtDqzdJOG_vPw_QJj8GjIRTRA1l80Ef-vlLe9XMzFYh-jUlK-jvDU1dhWyhp0sXYATR61CryBNS8ovLg8VN6QmppdsSr4y8TjM7E28ph5LECCvlLzz0oMAnReAg0KE8XqQYlT_GRdK0DScGIasDL8t9ZrzhVCkaU4lhOPtXFjHcDyUqD0WmYalyPyKylplH2m0FsQEJiXY88GQBqTwkOHGt_PeEeKQ3061OSqqu7Dmpg9zck4tzBT28n1PsP-EpEAKQMopxg9HLnGWHgP92H9ggXLTmweAJoY9fqv_8bK7-ZS1kpRaj7Ibh1cHg8ZyJMNlp7X5bX5J_HR_eCWyKeOa6R5PAyhOynpC3Hx4jmVUyfl8nY2VRH36aBzIJiHJF1fVvX77-gRbtI_VGDjiMCJ4-iOPc_xHNZe3Q--lGjzCzZwJEYkqepM5k8mxg94LcvfJ5gZlyIdNpr5PPMKtMuPqSlrqQXerfcD80_oVVTH5ALdWvxKUwtNemjjeY9t3eBqAjRTBvwgRLHwKDnFHbVxDbinsvzFPLd8NcinYbQ2gftQYxcA_tsvWv8T9jDDn7GNShqXc79f9fyl90R_UT1ZvwOaKqpJcZgZshkpSZ6xKiVVIsB74kQkaKPILqe5NYC4S5zKv_CuPVgeBqlVcCFapmFRci-rr7gjyX5_XjgS_56tJxHGD7xCwyf5GCWSYTSPoYZ_cjEdJCvduEll_cg4W_DmJahICZLyfI4ijBhWONmiVk2RT_pJ3wpLzBdflfURhKMdFCwPXjdmgnAxBepY7gWHInRIomkMSucbSN_E6b2ANkMXPm6xwhZUTjX1zznOtLl8MnouEDw7-iBBmiEuPPA3rF_C4Hpaqr0r3onj82ZZhOH2Vf7I1j2ZtdRuwgGaN4Hfj4Hw4pTvDUU-1LBvZo6UNvujPkm6iNkLwUCWNhQv-jpiTtMYiCialBhInvmYZo3nFEBM4_LTN10s-vuoT5HP5UaeNhc68qPNwiOTmxQhf1o1_9uy_VqeiS9Iq9Q2aOwYgSdSemQ3mJD2H3PIXtc-yoyeWMVwEb0rpUcExQKgNetk5wHjdH2AEEeRsKkRifZhURDxDkSg8WgXhMF_vbQI_s6SZcNZBbP0GxSxMRc4k0frvn2nV3St-qW4pTFdAWcKuDZtzNEyMkY8Vhxv6BfHCM5_RmSXpsXx3tzxclWrdBXqD9qWotwd6ElDy5Quqh4e8dH-LLdQhfDGzHinAF0tNruG_IGVJqdyA5qJEpQMuWrY81dBzqcQ4XmZMcpTtTtgQOooPEGkwXgUxM0Ck5pNYE-GnuIg9UfzgzzZyE87fFpWU646_4wEedMxNs2FKxhwnasSIcZtZ5NqkxDkqm5HAz1iJS5X9hrXSY5AUVagegSNLh3H8FADertRAmCTCCOo0NnMMwMggIWwIs2YqqGS1MX2-iFodb-mfSdaNe_3Sj5GrRV51nNHd3Y3OeaMjUMTQtpifYz15ayKl4gqdZCrnQAG3889mlNcZAhF6zaVdR5W27WJrMBgaRICYHYq4wYOnNV6suyjUvKdRwBdzWQ9aGUp-lGcLV9JSfVB_iC3Q5uBm0phII-1Xc1KaPJMnPkekZAbTX6YWA_tkLH1dBQZ-7CyW-J1dEcEfWzVo8VPVD1_gzSspSWWYwcNoGc6LgcoemvGHqxtXy0PKJ9QJKzzxoIX--EW7CKpCKcKDsTLKUi-OtjGRDbNEMT2RgZWBV86URLrC4VJi9flWO0gmkxGSA3BxmVWP7Kpa9-GwmI3MD1pC1lH5K0yT3Ho0K8V8wOkKRm9DG-go7hECGrABXzt5BDY-cIYhSL_qgUMahGjIhKNLe_w6hHZgKoA1At0Zh1LDpefBfOg5rjmIlG3n_HXfHigZqQ0DF5xcvbRR9UHGg2ncspvQs2mf8xiVAhKwocJLtB6ZHmydND4hKjoj40PhYpItWdgW_uimwtFadIqmqatHXElr1BAPgiyFHBj3lzsUQfaeDwbF_P8_0lBusBkNmaQIMVToNjE2mZoMKcONwPOykVST3Khx8pnBFQrB-vOTZy-cQlAIQ5fyZLNepKR_Egm3nLmeDgNR4OVehqjq857v6UmvybuzoGY6aEbYb4YNKI5po4f1jk3TPGsUkHndN4B05vwWGBEBk0aMutAchEyiscitijg8kSArGj2SaYlhh-RDgJtHmSjEErGIROy8ByaHj523qJTJsM4ZnkwuxIuXzVKrtXL_DEhmob4Uf0rDTVWNE_dDn4w686W6zXt9r6G0dW-B1ZT46yLrQ4Tui1n_WnSDxauIU46lPJpCJ1kwrB4HwKNvf34r2nz79VVP3ZDBl57zNpA3pXhNr92oLnAXX6hagpXm11Hv925pbAIeePqcuR2IlLPfoz8cfu_UTUz-Fi5p6ctS0FTZtAPKtwXeK_vLkDda6yvFdaXbt6qhNvrrc_TXKA4Uf7V2fk7564hjmiY3dQ8Gd63AZhl78sQRSsyYpkz11qb-WpRse0ZSgauORjvNNEX_hAU8sRUID8iUFI-xFyyjut60jSedCGgS07p38T5lZk4fGnVrNT7ltl4gEsWVsYerIIVmo3SawGQpvr6WKojrKe8iUnioHJd8WPvOWd13dREJj7Ls-ZCL9ZD2ypT8ckcYjUzRS8Byj5srCKkGUGWLPQxRDQaxx1kfL394ZOnpyXIuAhiAKMHxf26YzAvrB91wNXg50WVCNqHrzUXThuqNJgC-S2UOeragb3TUfCryL_tMdei2oNTQAdDodUfRmXot2cfG-gq79JJB_SGwnl6e7prMJR3djFrQgblWr7mE_AbBjwt7T8qovnJ4Lwj_yfykg11CBhChsHte-M3HsigMkLz85l0KNg9AueiJjTmXN6lEafKwwqG0OxzDht-yjE_PX2iZEZD1T4B1KD9R8R8fPQUlzZXgn8SYoAc-v4R9xwmjJX4zoODvnK_mNh8Kid0xLnYgp0mVwfg-ZYPPkZGGgZgxnXa7vjxVAjOCBBTUan9xPKfX18X-gr4I61W11Gk6RgyHy9sLEAQrtqTWyEyzqKyVm5bqMIb3u7UjFC8U7eEBEWDmXI3fGU5Hp9q5_He-d7LP_tMsuVqK9UxJ3i9Yz9_vrqtqhw94HYxEWo2Nb_IvAROJAGkBlPq7S7E5dr4G8FpARI4blU8DOJU-Y08FfIPTD3wMNkvwx_bCEFmQu_LLXvuZU_4ZacjMHq7LdW2lfjmrHHU4iQYmyzIUx1ZWJ9GVn3Bu2-Uv2h-FYdkQ4MDcPRPphjLla2U9SyUVvtMOruYlEozQiaO9LEsu7fxnZlhFlcCnu_LXVcbpLs0vfJ65vcdEQtFZjBHj697XJzFmWkUQuPNYRm591d_oH8Cj1u0zP7xnm1hvlWSimoXCUX4lDWdt6dlCXeTnF33miu3kVvR71yQ9MNiTFSNDLTr6QH3RxNsvWcutTmQnGXmKXJXR28KiETRwu8GMy44RPULukn8oXS0tloxwsrjUHbt3og_KbgLZOFk8JaTURqEKSLnLB-7dFTTfrdeEO_RdaI1hsnPLBndVn6iTqEKXstByTFKYxBplXLVTiocxqIZpZ3XMjZqlcY9WBId90QgS1_rUPFWbJF7a7emdezh0Tpp3tFi__OOYU9eM-Ibd_CmKlQHdDUT8NmyIhwAUdmcXgMM9uodrKoR8mpmz_FbIJ6vnBPAYJLtVJ5uHeLev7zQzKtH5TdM17zK8soeCIGZvt0Diki1QN8u0SURBmnYaD71XDDyt1-9Va-veVkKPAeyAbEDk8O8NG80ok06c6LyqB2mQA

**Comment by VinceFINET** [comment]
Is it linked to the "Performance edition" ????

**Comment by VinceFINET** [comment]
@vaumont did you succeed in installing on this sandbox because I see it on my subscribers list
![image](https://user-images.githubusercontent.com/3799275/111218640-48c0f480-85d7-11eb-85b3-4f1f77cda536.png)

**Comment by vaumont** [comment]
@VinceFINET 
No, I haven't been able to install it.
Not sure about the  edition. I'm still waiting to be granted  the proper BT access to decrypt  that stack trace.
Is OrgCheck officially  not supported on Performance Editions?

**Comment by VinceFINET** [comment]
Let's plan a quick call together to see what's happening when you log in to this org.

**Comment by VinceFINET** [comment]
The application is installed I think. 😄

**Comment by VinceFINET** [comment]
For the record, Vincent gave me feedback and the issue was that during installation the package needed to by-pass checking the existing apex code (with is in the org, not even in the orgcheck package).

I updated the screenshot used in the README
![](https://github.com/VinceFINET/OrgCheck/raw/main/Screenshots/OrgCheck-v1.9.1-Screenshot5.png)
