### ISSUE TITLE
Facing issue while installing OrgCheck managed package in my production Org

### ISSUE THREAD

**Issue by megha2695** [SalesforceLabs/OrgCheck#384]
I am encountering an issue while attempting to install the OrgCheck Managed package into my org. After providing the necessary credentials for my org, the installation process seems to initiate but ultimately fails. Upon inspection of the address bar, it appears that the process attempts to redirect to a signup page, but instead, I am met with an error screen.

Steps to Reproduce:

Navigate to the OrgCheck Managed package page.
Click on the "Get It Now" button.
Select the Salesforce option from the list and it will redirect to  -> login.salesforce.com/
Provide credentials for the org.
Observe the attempted redirection to a signup page and the subsequent error screen.

Expected Behavior:
The OrgCheck Managed package should install successfully into the org after providing credentials.

Actual Behavior:
The installation process fails, redirecting to a signup page and displaying an error screen instead.

Additional Information:

Org Type: Production Org
Browser: Google Chrome

I tried in Incognito Mode as well but failed to install this managed package. I'm also attaching the error screen page that I have received for your reference. Please investigate this issue and provide guidance on resolving it. Thank you for your assistance.
![Screenshot 2024-03-29 221912](https://github.com/SalesforceLabs/OrgCheck/assets/63503065/5f3ab01a-1483-466b-85af-a223e2237efb)

Megha Marwal

**Comment by VinceFINET** [comment]
Hello

Thank you for your ticket.
I am not sure this is specific to Org Check.

Are you able to install another listing from the appexchange with your user
?

Maybe you can log an issue to the appexchange team?

**Comment by megha2695** [comment]
Hello Team,

Yes, I can install other packages from the appexchange but I'm facing an
issue with my production org. I can install this package for my sandbox but
not my production org.

Please let me know if this is an issue with appexchange or with the
OrgCheck package.

**Comment by VinceFINET** [comment]
I believe the package is ok, as it has been installed on multiple
organisations productions or sandboxes.

it has to be something with the appexchange and your production org.

You should raise a ticket to the appexchange team instead.

Thank you

**Comment by VinceFINET** [comment]
@megha2695 Here is the feedback I received today from the team:
- can you make sure you were logged into your Trailblazer account when trying to install the package?
- can you check if your org is linked to your Trailblazer account?

Thank you

**Comment by VinceFINET** [comment]
is it ok? can i close this ticket as it appears not linked to my package whatsoever!
