### ISSUE TITLE
Installing from Github repo causes "An internal server error has occurred" error

### ISSUE THREAD

**Issue by lrockford** [SalesforceLabs/OrgCheck#385]
**Describe the bug**
When attempting to access the Org Check app after cloning from GitHub and pushing to sandbox org, only the Home tab loads, the superhero dog image with "Please wait while Org Check is loading..." never goes away, and this message shows up at the bottom of the page: "An internal server error has occurred Error ID: 0000000000-000000 (0000000000)". Enabling Lightning debug mode did not illuminate the issue.

**To Reproduce**
Clone the SalefsorceLabs/OrgCheck github repo. Deploy the force-app folder to a sandbox environment. Assign the "Org Check User" permission set to the running User in your sandbox. Attempt to access the Org Check App, note that the app tabs do not load correctly and the home page never loads.

**Comment by lrockford** [comment]
Note: We don't want to install the managed package because three tabs cause the app to crash for us; we want to be able to hide those tabs to prevent this situation. The unlocked package link is far out of date and is still using visualforce pages rather than LWC.

**Comment by VinceFINET** [comment]
Thank you for this issue.
I will try to reproduce the issue next week.

It is true that the Beryllium version (with LWC) is available on the main
branch of this repo. But the previous version (with Visualforce pages) is
still available on the appexchange.
I put the beryllium version on the main branch maybe too early in the UAT
process.

I am curious what is the error you have when installing the app from AppExc
or unlocked package.

**Comment by lrockford** [comment]
Understood! Maybe I can use the Visualforce version in the meantime, I made a bad assumption that the managed app was on lightning so I thought the unpackaged app was out of date. I will gather the issues we faced in our org and share with you, it was mainly around tabs crashing, likely due to the volume of some of our metadata.

The three pages I recall crashing were:
* Public Groups (never loads anything)
* Users (loads but crashes quickly after load, can't click on any links or do any scrolling, browser popup will pop and ask if we want to wait or reload after a while)
* Custom fields (same as users)

I'll try to provide more details in a follow up, would you prefer I open a new issue for these?

**Comment by VinceFINET** [comment]
yes please
