### ISSUE TITLE
Oh no, Org Check had an error!

### ISSUE THREAD

**Issue by vyerraguntla** [SalesforceLabs/OrgCheck#390]
**Describe the bug**
While we are trying to roles and role hierarchy we are getting the error  Oh no, Org Check had an error!

**To Reproduce**
Install org check and navigate to roles tab 

 Oh no, Org Check had an error!

**Comment by vyerraguntla** [comment]
Hi Team any update on this @VinceFINET

**Comment by VinceFINET** [comment]
Do you have more information like an error stack message?
What do you see in the browser console?
You need to give me more information about your error.

**Comment by vyerraguntla** [comment]
Hi Team,

Please find the below error which I have seen in the UI after I clicked on
Roles in the Org check . Any further information is needed . Please find
the stack message below

Stack:
INVALID_SESSION_ID: This session is not valid for use with the REST API
   at r.getError
(/resource/1715036552000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1715036552000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1715036552000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493
   at /resource/1715036552000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521
   at MutationObserver.o
(/resource/1715036552000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)

[image: image.png]

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Team please find the help article if this is some thing related to
https://help.salesforce.com/s/articleView?id=000387018&type=1

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi Team,

Could you please confirm if we have any update on the same .

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi @VinceFINET Any update on the same. We are awaiting your reply as it is preventing us to run org check on customer org

**Comment by VinceFINET** [comment]
The link you provided refers to connected apps.
Org Check is not using such settings.
It gets the user access token from Visualforce directly.

**Comment by vyerraguntla** [comment]
Thank you. But please let me know how to resolve the error that we received.

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi Team,

Any update on this ? We have dependency on the org check to perform Annual
Technical Health Review . Could you please prioritize it and let us know if
any further assistance is required.

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by VinceFINET** [comment]
Please refer to this issue it might resolve yours:  #118

**Comment by VinceFINET** [comment]
Refering to the documentation https://salesforcelabs.github.io/OrgCheck/installation/

<img width="745" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/52a3eb59-70fd-4b95-a2e8-5a15be68e364">

**Comment by vyerraguntla** [comment]
Thank you for your response Vincent. We will check it out and get back to
you if the issue persists.

Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi Vincent,

Thanks for the update . The issue has been resolved.

Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>
