### ISSUE TITLE
Error at the visual componenets TAB

### ISSUE THREAD

**Issue by syslap** [SalesforceLabs/OrgCheck#40]
Error #0: UNKNOWN_EXCEPTION
When: While creating a promise to call "private_query".
What:
index: 4
queryMore: false
queryString: SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE RefMetadataComponentId IN ('0998E0000002TUL','0998E0000002TUM','0998E0000002TUN','0998E0000002TUO','0998E0000002TUP','0998E0000002TUQ','0998E0000002TUR','0998E0000002TUS','0998E0000002TUT','0668E000001QPky','0668E0000002OSd','0668E0000002UQB','0668E0000002C4P','0668E0000002C4Q','0668E0000002C4R','0668E0000002C4S','0668E0000002C4T','0668E0000017VZT','0668E0000017VZU','0668E0000003oki','0668E0000001Rx4','0668E0000005jGM','0668E0000005jGN','0668E0000005jGO','0668E0000005jGP','0668E0000005jvc','0668E0000005jGF','0668E0000005jGG','0668E0000005jGH','0668E0000005jGI','0668E0000005jGJ','0668E0000005jGK','0668E0000005jGL','0668E0000005jGQ','0668E0000005jGR','0668E0000005jGS','0668E0000005jGT','0668E0000005jGU','0668E0000005jGV','0668E0000001XTk','0668E0000001WME','0668E0000002MBz','0668E0000002MC0','0668E0000002MC1','0668E0000002MC2','0668E0000002MC3','0668E0000001bqs','0668E000000gCNJ','0668E000000XVo2','0668E000000XVo3') OR MetadataComponentId IN ('0998E0000002TUL','0998E0000002TUM','0998E0000002TUN','0998E0000002TUO','0998E0000002TUP','0998E0000002TUQ','0998E0000002TUR','0998E0000002TUS','0998E0000002TUT','0668E000001QPky','0668E0000002OSd','0668E0000002UQB','0668E0000002C4P','0668E0000002C4Q','0668E0000002C4R','0668E0000002C4S','0668E0000002C4T','0668E0000017VZT','0668E0000017VZU','0668E0000003oki','0668E0000001Rx4','0668E0000005jGM','0668E0000005jGN','0668E0000005jGO','0668E0000005jGP','0668E0000005jvc','0668E0000005jGF','0668E0000005jGG','0668E0000005jGH','0668E0000005jGI','0668E0000005jGJ','0668E0000005jGK','0668E0000005jGL','0668E0000005jGQ','0668E0000005jGR','0668E0000005jGS','0668E0000005jGT','0668E0000005jGU','0668E0000005jGV','0668E0000001XTk','0668E0000001WME','0668E0000002MBz','0668E0000002MC0','0668E0000002MC1','0668E0000002MC2','0668E0000002MC3','0668E0000001bqs','0668E000000gCNJ','0668E000000XVo2','0668E000000XVo3')
queryUseTooling: true
UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 124376481-29959 (-384889215)
   at h.getError (https://engiedgpfr--pprdedgpfr--orgcheck.cs87.visual.force.com/resource/1612955729000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://engiedgpfr--pprdedgpfr--orgcheck.cs87.visual.force.com/resource/1612955729000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://engiedgpfr--pprdedgpfr--orgcheck.cs87.visual.force.com/resource/1612955729000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://engiedgpfr--pprdedgpfr--orgcheck.cs87.visual.force.com/resource/1612955729000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://engiedgpfr--pprdedgpfr--orgcheck.cs87.visual.force.com/resource/1612955729000/orgcheck__OrgCheck_JSForce_SR:4:7059)

**Comment by VinceFINET** [comment]
thank you @syslap for this issue. 
I hope you had a nice demo of the tool even though you had this error!!!

do you reproduce this error everytime on the same page? 
what happens if you clean the cache, close the browser etc. ???

**Comment by VinceFINET** [comment]
@syslap could you try to query from Workbench on the REST Explorer the tooling API?
using `/tooling/query?q=SELECT....`

With the complete query:

```
SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, 
   RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE
   RefMetadataComponentId IN ('0998E0000002TUL','0998E0000002TUM','0998E0000002TUN','0998E0000002TUO', 
  '0998E0000002TUP','0998E0000002TUQ','0998E0000002TUR','0998E0000002TUS','0998E0000002TUT',
  '0668E000001QPky','0668E0000002OSd','0668E0000002UQB','0668E0000002C4P','0668E0000002C4Q', 
  '0668E0000002C4R','0668E0000002C4S','0668E0000002C4T','0668E0000017VZT','0668E0000017VZU', 
  '0668E0000003oki','0668E0000001Rx4','0668E0000005jGM','0668E0000005jGN','0668E0000005jGO', 
  '0668E0000005jGP','0668E0000005jvc','0668E0000005jGF','0668E0000005jGG','0668E0000005jGH', 
  '0668E0000005jGI','0668E0000005jGJ','0668E0000005jGK','0668E0000005jGL','0668E0000005jGQ', 
  '0668E0000005jGR','0668E0000005jGS','0668E0000005jGT','0668E0000005jGU','0668E0000005jGV', 
  '0668E0000001XTk','0668E0000001WME','0668E0000002MBz','0668E0000002MC0','0668E0000002MC1', 
  '0668E0000002MC2','0668E0000002MC3','0668E0000001bqs','0668E000000gCNJ','0668E000000XVo2', 
  '0668E000000XVo3') OR MetadataComponentId IN 
  ('0998E0000002TUL','0998E0000002TUM','0998E0000002TUN','0998E0000002TUO','0998E0000002TUP', 
  '0998E0000002TUQ','0998E0000002TUR','0998E0000002TUS','0998E0000002TUT','0668E000001QPky',
  '0668E0000002OSd','0668E0000002UQB','0668E0000002C4P','0668E0000002C4Q','0668E0000002C4R',
  '0668E0000002C4S','0668E0000002C4T','0668E0000017VZT','0668E0000017VZU','0668E0000003oki',
  '0668E0000001Rx4','0668E0000005jGM','0668E0000005jGN','0668E0000005jGO','0668E0000005jGP',
  '0668E0000005jvc','0668E0000005jGF','0668E0000005jGG','0668E0000005jGH','0668E0000005jGI',
  '0668E0000005jGJ','0668E0000005jGK','0668E0000005jGL','0668E0000005jGQ','0668E0000005jGR',
  '0668E0000005jGS','0668E0000005jGT','0668E0000005jGU','0668E0000005jGV','0668E0000001XTk',
  '0668E0000001WME','0668E0000002MBz','0668E0000002MC0','0668E0000002MC1','0668E0000002MC2',
  '0668E0000002MC3','0668E0000001bqs','0668E000000gCNJ','0668E000000XVo2','0668E000000XVo3')
```

**Comment by VinceFINET** [comment]
any update @syslap ?

**Comment by VinceFINET** [comment]
Duplicate of #73

**Comment by VinceFINET** [comment]
H! 

The Dependency API PM told me that customers should create a ticket to Salesforce support about this issue so that we can open an investigation.

By any chance if you still have this issue, could you create that ticket and send me the number of the case in PM? 
Thank you

**Comment by VinceFINET** [comment]
See #488
