### ISSUE TITLE
We are getting error while clicking on users Tab in Org check  -- ERROR_HTTP_400 issue

### ISSUE THREAD

**Issue by vyerraguntla** [SalesforceLabs/OrgCheck#408]
We are getting below error when we click on Users  Tab in Org check  with error as Access Denied. Error stack is mentioned below 

I
**To Reproduce**
ssue #0: ERROR_HTTP_400
When: While creating a promise to call a SOQL query.
What:
index: 0
queryMore: undefined
queryString: SELECT Id, Name, SmallPhotoUrl, Profile.Id, Profile.Name, LastLoginDate, LastPasswordChangeDate, NumberOfFailedLogins, UserPreferencesLightningExperiencePreferred, (SELECT PermissionSet.Id, PermissionSet.Name, PermissionSet.PermissionsApiEnabled, PermissionSet.PermissionsViewSetup, PermissionSet.PermissionsModifyAllData, PermissionSet.PermissionsViewAllData, PermissionSet.IsOwnedByProfile FROM PermissionSetAssignments ORDER BY PermissionSet.Name) FROM User WHERE Profile.Id != NULL AND IsActive = true
queryUseTooling: undefined
Stack:
ERROR_HTTP_400: Access Declined
   at r.getError (/resource/1714768175000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1714768175000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1714768175000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493
   at /resource/1714768175000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521
   at MutationObserver.o (/resource/1714768175000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)

**Comment by VinceFINET** [comment]
Some questions:
- is this error only appear for this tab?
- how many active users do you have in this org?
- are they assigned to multiple permission sets? What is the avg / min /
max number of perm sets assigned to active users?

**Comment by vyerraguntla** [comment]
Hi Vincent,

- is this error only appearing for this tab?- This is happening for the tab
USERS
- is this error only appearing for this tab? There are around 2000 active
users in the org
- are they assigned to multiple permission sets? What is the avg / min /-
On average each user is having around 50+ permissions assigned .

Please let me know if any further information is needed .

 Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi Vincent,

Could you please confirm if we have any update on the same


Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by VinceFINET** [comment]
Hello

Could you run the queries i mentioned in issue #413 and put the results here?
Thank you

**Comment by VinceFINET** [comment]
some update @vyerraguntla by any chance?

**Comment by vyerraguntla** [comment]
Thank you Vincent. My apologies, I forgot this. We have ran some SOQL
queries which resolved the issue.
Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>
