### ISSUE TITLE
Unable to Install this product from app Exchange

### ISSUE THREAD

**Issue by narendrakona123** [SalesforceLabs/OrgCheck#414]
Hi Team,

When i try to install org check package from app exchange , its getting below error.

Package Not Found | The requested package doesn't yet exist or has been deleted. If this is a recently created package version, please try again in a few minutes or contact the package publisher.

Can you pls suggest any other version package is active ?

**Comment by VinceFINET** [comment]
The listing in AppExchange is using the version called Lithium v3.2.0 and this version is not deprecated:
<img width="182" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/1685cc27-2124-4ed1-8498-f818249c73d3">
<img width="167" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/2bed7fe1-0546-4b0a-b85d-e8c6cdd7aab3">

This version should work on your org.

Question:
- Can you test in another org?
- Can you give me the org id where the package cannot be installed?

**Comment by VinceFINET** [comment]
What is the status of your issue @narendrakona123 ?

**Comment by narendrakona123** [comment]
@VinceFINET  Thank you . 

I tried to install another dev org . its started working without any issues . thank you for your support

**Comment by narendrakona123** [comment]
@VinceFINET  issue resolved
