### ISSUE TITLE
While re-compiling the Apex class

### ISSUE THREAD

**Issue by akonduri77** [SalesforceLabs/OrgCheck#416]
**Describe the bug**
We have installed Org Check app in our Organization We see the Apex classes and Batch classes to Compile while installing the app.
When we re-compiling the apex classes and Batch classes we see the error attached below.
<img width="434" alt="Org check " src="https://github.com/SalesforceLabs/OrgCheck/assets/170518949/5212f2e9-3db9-44e1-bd84-3e1cf6b3f08a">
 

**To Reproduce**

After installing the Org check app from App exchange we need to click on the Apex class component.

**Comment by VinceFINET** [comment]
How many classes that need recompilation do you have in this org?

**Comment by akonduri77** [comment]
Hi Vince,

Here i have attached the error which we faced and the classes details in the screenshot.
![Uploading image.png…]()

**Comment by akonduri77** [comment]
![image (1)](https://github.com/SalesforceLabs/OrgCheck/assets/170518949/e60171b6-75af-4f77-85e7-a0c30a15f7bc)
Attached one more Screenshot please check

**Comment by VinceFINET** [comment]
dear @akonduri77 
How many classes do you have (before this error message) that needed recompilation in this org?
There is an open issue about this so i just wanted to make sure this is the same or something else?

**Comment by VinceFINET** [comment]
the issue i am referring to is #256

**Comment by VinceFINET** [comment]
Solved in Beryllium 
<img width="1079" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/8938b283-0c40-4eae-9d07-5aa775f41654">
