### ISSUE TITLE
Idea : export the dependency images to create great documentations

### ISSUE THREAD

**Issue by jalal3107** [SalesforceLabs/OrgCheck#42]
Hello Vincent,

Is it possible de print the dependency image, WE need to use them in our technical documentations.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/24570415/110005307-9eb0b500-7d18-11eb-92fa-95d831ea7076.png">

Best regards,

**Comment by VinceFINET** [comment]
The modal dialog will have an export button on the footer.

So this means that the content of the dialog box will be exportable as an HTML file (whatever the content and the use case)
This includes the case where you have a dependency diagram (which is an SVG).

![image](https://user-images.githubusercontent.com/3799275/110095355-1fb19000-7d9d-11eb-909f-599bfb502d6e.png)

Good to go for next version 1.9.2
