### ISSUE TITLE
Profile & Permission Set Report No Showing User Count

### ISSUE THREAD

**Issue by macalmon** [SalesforceLabs/OrgCheck#434]
**Describe the bug**
When viewing the Profiles and Permission Set reports under the Profile and Permission Sets sub-tabs the "#Active Users" column is not rendering properly. I know I have users in these that are say "No internal active users"

**To Reproduce**
Run the report

![image](https://github.com/user-attachments/assets/e5196270-1f45-480c-986f-d634b0a756bc)

**Comment by VinceFINET** [comment]
Hi

Thank you for creating this issue.

The column called "#Active users" is the "memberCounts" property for either permission set or profile in Org Check.
This is calculated based on the number of active users assigned to the pset or profile.

Looking at the code it seems to be good for Permission Set: 
We look at PermissionSetAssignment table 
see https://github.com/SalesforceLabs/OrgCheck/blob/a539addd3668efa5e058341f6ec64d8e0c6a7a43/force-app/main/default/lwc/orgcheckApp/api/dataset/orgcheck-api-dataset-permissionsets.js#L20
set the count to zero
see https://github.com/SalesforceLabs/OrgCheck/blob/a539addd3668efa5e058341f6ec64d8e0c6a7a43/force-app/main/default/lwc/orgcheckApp/api/dataset/orgcheck-api-dataset-permissionsets.js#L53
And increment the count in the code for each perset
see https://github.com/SalesforceLabs/OrgCheck/blob/a539addd3668efa5e058341f6ec64d8e0c6a7a43/force-app/main/default/lwc/orgcheckApp/api/dataset/orgcheck-api-dataset-permissionsets.js#L85

OK good.

When i check the same for profiles:
We set that property to zero
BUT somehow never increase it.
see https://github.com/SalesforceLabs/OrgCheck/blob/a539addd3668efa5e058341f6ec64d8e0c6a7a43/force-app/main/default/lwc/orgcheckApp/api/dataset/orgcheck-api-dataset-profiles.js#L42

That's a very good catch.
and i believe this deserves an Org Check sticker (and other salesforce ones).
DM your postal address on social or by email (not here obviously) and i'll send it to you as soon as i can!!

MERCI!

**Comment by VinceFINET** [comment]
Dear @macalmon 

I fixed the issue in the code, I need to package the app so you can use it in your org!
