### ISSUE TITLE
Unable to get data from Custom Fields in new version of Org check 

### ISSUE THREAD

**Issue by vyerraguntla** [SalesforceLabs/OrgCheck#436]
**Describe the bug**
When we click on custom fields in new org check we are getting error as "ERROR_HTTP_400: Access Declined
    at r.getError (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/usa934s.sfdc-8tgtt5/auraFW/javascript/RmVZUWhmMHM5OTNFTmVCOE0ydnJTd2pxSXZJTGVxSHY0OVdtaERiQXFxSFE5LjE5Mi4w/aura_prod.js:105:100625)), <anonymous>:3:72751)

**To Reproduce**

Go to org check and click on custom fields Tab

**Comment by VinceFINET** [comment]
Hello

thank you for raising an issue!

Is this error only occuring when clicking on the custom fields tab? or also in other tabs?
can you screenshot the whole dialog box please?
the error is direclty showing up or is it after some seconds?

what is the result of the following query in your org?
`SELECT COUNT(Id) FROM CustomField WHERE ManageableState IN ('installedEditable', 'unmanaged')`

do you have the same error if from the home tab you first filter with an object (for example "Account" and then go to the custom fields tab?

Thank you.

**Comment by vyerraguntla** [comment]
Hi Vincent,

Thanks for looking into it.


   1. In this use case  we are having the issue only in the custom fields
   not on other tabs
   2. Please find the below screenshot which we got when we clicked on
   Custom Fields
   3. This error is coming up after spinning for ~10 seconds
   4. SELECT COUNT(Id) FROM CustomField WHERE ManageableState IN
   ('installedEditable', 'unmanaged')
   5. The result of above query gives 12681 fields.Yes even if I click on
   particular object also it is failing to load with same error as mentioned
   below


*Note* :- We had similar instance last week for one of the org , but it got
resolved after we reinstalled the org check but that  workaround is not
working for this use cause

[image: Screenshot 2024-09-10 at 4.55.56 PM.png]


Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by VinceFINET** [comment]
This happens when the app is using "too many" queries in parallel and salesforce front servers sees this as a thread. see https://github.com/SalesforceLabs/OrgCheck/issues/74

so need to reproduce your env with 12k custom fields with dependencies and all...

**Comment by vyerraguntla** [comment]
Thanks Vincent . Do you want us to schedule some call with you to
troubleshoot further?

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by vyerraguntla** [comment]
Hi Vincent,

Could you please let us know your availability for a 30 minutes call. Few
of our engineers have identified other issues with the org check and we use
org check extensively for one of our internal projects .  We just want to
check with you before logging bugs

Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by VinceFINET** [comment]
Let’s plan this before DF.

Le mar. 10 sept. 2024 à 22:29, vyerraguntla ***@***.***> a
écrit :

> Hi Vincent,
>
> Could you please let us know your availability for a 30 minutes call. Few
> of our engineers have identified other issues with the org check and we
> use
> org check extensively for one of our internal projects . We just want to
> check with you before logging bugs
>
> Regards,
> Varun Kumar
> Sr. Proactive Monitoring Engineer | Salesforce
>
> <https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>
>
>
> On Tue, Sep 10, 2024 at 8:32 PM Varun Kumar Yerraguntla <

**Comment by vyerraguntla** [comment]
Sure Vincent. Could you please let us know your work timings so we can
schedule call accordingly and please let us know your email as well.

Regards,
Varun Kumar
Sr. Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by chrystal-reiily** [comment]
Hi There,
Do we know when this is due to be resolved? We are also experiencing this issue. Many thanks

<img width="670" alt="org check error" src="https://github.com/user-attachments/assets/d0040af8-f114-4303-b602-27e8c87a98ae">

**Comment by sarahkhalid2** [comment]
Hi Vince, I am running into the same issue on the Custom Fields tab.
<img width="1003" alt="Screenshot 2024-10-11 at 10 10 24 AM" src="https://github.com/user-attachments/assets/d2f0b469-89e7-47fe-a2d3-17d330eb9a28">

**Comment by VinceFINET** [comment]
hello @sarahkhalid2 @chrystal-reiily @vyerraguntla 

since yesterday's update do you have still this error in the app?
thank you.

**Comment by vyerraguntla** [comment]
Hi Vincent,

Could you please where the link for new version of org check so we can
check .

Regards,
Varun Kumar
Proactive Monitoring Engineer | Salesforce

<https://smart.salesforce.com/sig/vyerraguntla//us_mb/default/link.html>

**Comment by chrystal-reiily** [comment]
Hi,
Yes it is still happening,
Chrystal

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VinceFINET** [comment]
Hello @sarahkhalid2 @chrystal-reiily @vyerraguntla 

could you all send me the orgId (starting with 00D), the current userid (starting with 005) and the timeframe start/end (in UTC) when this error occurs  in your org so I can check the logs please?

Thank you

**Comment by VinceFINET** [comment]
Example:
- OrgId: `00D0N000000q9gT `
- UserId: `0050N00000A04asQAB`
- Start Date: `2024-10-17T18:18:43.037+00:00`
- End Date: `2024-10-17T18:27:27.037+00:00`

**Comment by VinceFINET** [comment]
and the rest of the app is working right ??

**Comment by VinceFINET** [comment]
under my radar this log is super vague and might hide an issue indeed 
<img width="620" alt="image" src="https://github.com/user-attachments/assets/1028ff12-091f-4acc-97f8-e024c18c7912">

**Comment by VinceFINET** [comment]
Thanks @sarahkhalid2 for your help on this.

So to give the community more details about the status ot this (last) issue for Beryllium...

This error "400 Access Declined" is not an error thrown by the Salesforce API at all!
It is a hard coded httpCode and httpBody that is set by jsforce in case the XHR receives no status code...
Please check this specific line: https://github.com/jsforce/jsforce/blob/release-1.9.3/lib/browser/request.js#L53

that line is present from the beginning of the project in branch 1.x, so not sure it is the root cause but for sure this is related...

Also i see that from the HAR sarah sent me that some queries (to the composite tooling endpoint) have NO RESPONSE....
So i am still investigating...

**Comment by VinceFINET** [comment]
so going back to you as this is clearly related to the library used in chrome not having enough resources from the browser
root cause is: net::ERR_INSUFFICIENT_RESOURCES

**Comment by VinceFINET** [comment]
I know it sounds crazy but could you test Org Check from firefox and tell me if this is working better?

**Comment by VinceFINET** [comment]
And there is no point migrating to a new version of jsforce because the code is there https://github.com/jsforce/jsforce/blob/3.2.2/src/browser/request.ts

**Comment by VinceFINET** [comment]
some work have been done on optimising the number of requests ran on the composite/tooling api. let's test !!!
