### ISSUE TITLE
Insufficient Privileges when Clicking Public Group and Queue links

### ISSUE THREAD

**Issue by tobinman709** [SalesforceLabs/OrgCheck#450]
When clicking on public group or queue links in Orgcheck I am brought to a page that says insufficient privileges. The other component links work correctly. Has anyone experienced this issue before?

Also I am finding orgcheck opens a lot of components in classic mode is there anyway to control this?

I do not see any app options available to change. 

Any help would be greatly appreciated overall this seems like a very useful tool.

Thanks,
Tyler

**Comment by VinceFINET** [comment]
dear Tyler

thank you for raising this issue.

for the first part of your issue

this is indeed an error in the code that creates the setup url for the queue or the public group.

i was able to reproduce very easily this.
<img width="562" alt="image" src="https://github.com/user-attachments/assets/56bf281e-7825-4c18-90e4-02fea045ba41">

For example the URL of a public group is https://orgcheckvalidation-dev-ed.my.salesforce.com/00G7Q000004M8nwUAC
Where it should be not just the id but something else.

I will correct this asap. 
Thank you.

**Comment by VinceFINET** [comment]
For the second part of your issue let's create another issue to separate the scope of each ticket.
i'll do that for you don't worry.
#451

**Comment by VinceFINET** [comment]
Code to improve is the following:

https://github.com/SalesforceLabs/OrgCheck/blob/f65c7bb89a0b06d5aab0e47ce479610f7ad17429/force-app/main/default/lwc/orgcheckApp/api/core/orgcheck-api-sfconnectionmanager.js#L96

needs a new case statement for puvlic group and queue.

**Comment by tobinman709** [comment]
Hello, Thanks for your help with this.

How do I go about installing this code upgrade do I need to update to a newer version or manually change the code?

Thanks,
Tyler

**Comment by tobinman709** [comment]
Hello,

any update on this code fix?

Thank you for your support.

Tyler

**Comment by VinceFINET** [comment]
deployed!
