### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by calebsidel** [SalesforceLabs/OrgCheck#455]
**Describe the bug**
Loaded the User tab.
Clicked on "export" button - nothing happens

Loaded Profiles tab
Clicked on "export" button - nothing happens

**To Reproduce**
Using latest version of Firefox, no ad blocks, no extensions
In Production, did the waiver drop down
Loaded the User tab.
Clicked on "export" button - nothing happens

**Comment by VinceFINET** [comment]
Hello thank you for raising this ticket. 

Are you using the last version called Beryllium? (the version is on the home page) 
if not go to AppExchange and upgrade the package
<img width="428" alt="image" src="https://github.com/user-attachments/assets/3b4a042a-0b9a-4928-bcf6-2ec1071b115a">


How many users and profile do you see in the application?

**Comment by VinceFINET** [comment]
in parallel i am testing on Firefox... (honestly the last time i tested in Firefox was like 3 months ago sorry about that !!)

indeed all the export buttons in firefox from the app are not working. 
i'll check that !!

**Comment by VinceFINET** [comment]
could it be the root cause ?

<img width="899" alt="image" src="https://github.com/user-attachments/assets/cc7fa9d3-2ae3-4c37-9788-f6b33179bf21">

**Comment by VinceFINET** [comment]
interesting article: https://git.sheetjs.com/sheetjs/sheetjs/issues/3145

**Comment by VinceFINET** [comment]
Awesome!! the button will work now on FF in the next subversion of Beryllium!

**Comment by calebsidel** [comment]
Thank you Vincent! And sorry I don't get emails from these GitHub comments so didn't realize I owed you responses. Yes it was "Welcome in Org Check (Beryllium [Be,4])". But all of that is not so relevant anymore as you've fixed it! Thank you!

**Comment by VinceFINET** [comment]
deployed!
