### ISSUE TITLE
Flows Listed As 'No Description' despite having one

### ISSUE THREAD

**Issue by tobinman709** [SalesforceLabs/OrgCheck#456]
Hello,

We are trying to do some technical debt cleanup around flows and we are trying to deal with the no description flag which is listed for some flows. However we are finding that the no description flag is being shown for flows that 100% have a description. Is there a reason this is still showing up?

What requirements have to be met for this flag to disappear?

Would you be able to hop into a quick call so I could show you what I am talking about?

Thanks,
Tyler

**Comment by tobinman709** [comment]
Hello,

One update to provide. When I go into the flow version page on the flows flagged as no description (but they have one) and then click edit and save. The flow is now not flagged as having no description. Is this a glitch? These flows certainly have a description but I need to resave the description on the versions page in order for orgcheck to recognize it. 

If you want to get onto a quick call I can show you exactly what I am talking about.

Thanks,
Tyler

**Comment by VinceFINET** [comment]
the column "its definition" refers to the current version of the flow 
<img width="288" alt="image" src="https://github.com/user-attachments/assets/1fa68014-7b4f-453e-bdd6-25cb988f493e">

This refers in the setup menu to the description of the current versio of the flow
in the following example none of the versions have description.
<img width="562" alt="image" src="https://github.com/user-attachments/assets/a8d1ce16-8250-4622-9c4f-f65d64ac122e">

the column "description" refers to the version of the flow definition (the root if you will of all the versions of the same flow)
<img width="239" alt="image" src="https://github.com/user-attachments/assets/c02fd04c-74c7-4cbd-ba13-210ad4392b44">

This refers in the setup to the main descrption of the flow (whatever the current version)
in the followiong example the description of the flow is "description" (ho boy!!)
<img width="608" alt="image" src="https://github.com/user-attachments/assets/23c10883-3fde-46b8-af29-3612d3b2e2e8">

**Comment by VinceFINET** [comment]
I don't think this is a bug. the distingction between the description of the flow and its current version is not so clear... that's all. but not a bug.

ok for you @tobinman709 ?
