### ISSUE TITLE
Oh no, Org Check had an error!

### ISSUE THREAD

**Issue by apadole1** [SalesforceLabs/OrgCheck#458]
Describe the bug
While we are trying to access Apex Classes we are getting the error Oh no, Org Check had an error!

To Reproduce
Install org check and navigate to Apex Classes

Oh no, Org Check had an error!

More details:

Salesforce Information
Salesforce API Version: 62
Installed on OrgId: 00DAq000006Cx5i
Type of this org: undefined
Current running UserId: 005Aq00000MzWloIAF
Current Daily Api Requests: {"apiUsage":{"used":74,"limit":32007800}}

Navigation Information
Page: /apex/OrgCheck_ApexComponents_VFP

System Information
Language: en-GB

Issue #0: INSUFFICIENT_ACCESS
When: While creating a promise to call a SOQL query.
What:
index: 3
queryMore: undefined
queryString: SELECT ApexClassId FROM AsyncApexJob WHERE JobType = 'ScheduledApex'
queryUseTooling: undefined
Stack:
INSUFFICIENT_ACCESS: Requires Extra Verification
   at r.getError (/resource/1730740070000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1730740070000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1730740070000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493
   at /resource/1730740070000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521
   at MutationObserver.o (/resource/1730740070000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
<img width="1728" alt="Screenshot 2024-11-19 at 12 00 05 AM" src="https://github.com/user-attachments/assets/669208a3-9853-4a46-b452-bbc0f18ea6bd">

**Comment by VinceFINET** [comment]
Hello thank you for you ticket.
Can you upgrade the version of package your using in this org?
To do so, go to https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000HA0X2UAL
Then install the new package on the same org it will update the app.
I am sure it will solve your issue.

**Comment by apadole1** [comment]
![Screenshot 2024-11-20 at 5 07 14 AM (2)](https://github.com/user-attachments/assets/bcca6dd7-7317-4fed-a153-d6acadad89f9)
Hi Team,

Even after upgrading the org check to the latest version we are getting the same error.

Error details:

INSUFFICIENT_ACCESS: Requires Extra Verification
    at r.getError (https://finning--athr--orgcheck.sandbox.vf.force.com/resource/1732058472000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://finning--athr--orgcheck.sandbox.vf.force.com/resource/1732058472000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://finning--athr--orgcheck.sandbox.vf.force.com/resource/1732058472000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://finning--athr--orgcheck.sandbox.vf.force.com/resource/1732058472000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://finning--athr--orgcheck.sandbox.vf.force.com/resource/1732058472000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://static.lightning.force.com/can2s.sfdc-58ktaz/auraFW/javascript/dzlEdDRVZ1RsVXFtVkduczVYNVVfZ1ZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:92:91773)
    at e.<computed> (https://static.lightning.force.com/can2s.sfdc-58ktaz/auraFW/javascript/dzlEdDRVZ1RsVXFtVkduczVYNVVfZ1ZuNVJhc1EyaHA2ZTdMUkxCNEw5Y1E5LjMyMC4y/aura_prod.js:46:4529)

**Comment by VinceFINET** [comment]
Do you have Shield Platform Encryption in this Org among with the following
setting:
Manage Encryption Keys is set to "Raise session to high assurance"

https://issues.salesforce.com/issue/a028c00000j5kSTAAY/insufficient_access-requires-extra-verification-while-deploying-metadata-when-manage-encryption-keys-is-set-to-raise-session-to-high-assurance

**Comment by VinceFINET** [comment]
Or do you have set the “Identity Verification Setting” (Setup > Security Controls > Identity Verification) to "Raise session to high assurance" for all the operations?

https://help.salesforce.com/s/articleView?id=000389171&type=1

**Comment by VinceFINET** [comment]
What do you have on this page /lightning/setup/IdentityVerification/home ?
<img width="832" alt="image" src="https://github.com/user-attachments/assets/dde3d952-ee2d-4784-a8d0-a87a76bd4c80">

**Comment by apadole1** [comment]
Hi Team,

We could see Manage Encryption Keys is set to "Raise session to high assurance" and could also see other permissions set to "Raise session to high assurance". Could you please help letting us know which permission should be changed as it is a sandbox org for customer's metadata analysis.

**Comment by apadole1** [comment]
<img width="1728" alt="Screenshot 2024-11-21 at 1 54 27 AM" src="https://github.com/user-attachments/assets/1aa5632b-e2c4-4a4e-a8c8-f3fe9b47682b">

**Comment by apadole1** [comment]
![Uploading Screenshot 2024-11-21 at 1.54.23 AM.png…]()

**Comment by apadole1** [comment]
<img width="1728" alt="Screenshot 2024-11-21 at 1 54 23 AM" src="https://github.com/user-attachments/assets/2c162ba9-ad88-422d-8637-d9de2b957181">

**Comment by VinceFINET** [comment]
Hello

In my dev org i reproduced the error when one of the two options are set to either BLOCK or RAISE SESSION TO HIGH ASSURANCE
- Manage Sharing
- Manage Users

The help text of the option `Manage Sharing` is  `Controls access to the Sharing Settings Setup page, the SharingRules object, and the CustomObject’s sharingModel field in the Metadata API.`

The help text of the option `Manage Users` is  `Controls access to the Users Setup page.`

Clearly these two options have an impact when using Salesforce REST API to query the Organization table.
The query is ```SELECT Id, Name, IsSandbox, OrganizationType, TrialExpirationDate, NamespacePrefix FROM Organization LIMIT 1```

**Comment by apadole1** [comment]
Thanks Vince,

Will try to make changes in these permissions and will let update you on the same.

Best Regards!

**Comment by apadole1** [comment]
Thanks Vince,

But could see both the permissions are set to NONE for this org. Should I change it?

**Comment by apadole1** [comment]
Thanks Vince,

When I changed Manage Data Export setting to NONE, the issue got resolved. Cool!

Best Regards!

**Comment by VinceFINET** [comment]
I think i will just document this error in the web site... Thank you for your participation on making Org Check a more stable tool.

**Comment by VinceFINET** [comment]
Changed!
https://salesforcelabs.github.io/OrgCheck/installation/

<img width="796" alt="image" src="https://github.com/user-attachments/assets/58fa2887-86e8-403c-bc64-749a29533401">
