### ISSUE TITLE
Problem in running Batches

### ISSUE THREAD

**Issue by Nichneo** [SalesforceLabs/OrgCheck#46]
OrgCheck Information
Version: v1.8.3
Navigation Information
Page: /apex/OrgCheck_Batches_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Operating System: Win32
Language: es-ES

Error #0: EXCEEDED_ID_LIMIT
When: While creating a promise to call "private_query".
What:
index: 0
queryMore: undefined
queryString: SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, COUNT(Id) ids, SUM(NumberOfErrors) errors FROM AsyncApexJob WHERE ExtendedStatus <> NULL OR Status = 'Failed' GROUP BY JobType, ApexClass.Name, MethodName, Status, ExtendedStatus
queryUseTooling: false
EXCEEDED_ID_LIMIT: Aggregate query does not support queryMore(), use LIMIT to restrict the results to a single batch
   at h.getError (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:4:7059)

Error #1: TypeError
TypeError: Cannot read property 'm' of undefined
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_OrgCheck_SR:1140:44

**Comment by VinceFINET** [comment]
Thank you for using OrgCheck and share your issue with the community.
I see you are using 1.8 (see in the log "Version: v1.8.3")
I pushed you the last version 1.9.

Do you reproduce the issue with this new version?

**Comment by Nichneo** [comment]
Hi Vince,
yes, here the new error:
OrgCheck Information
Version: v1.9.1
Installed on OrgId: 00D58000000K3E6

Navigation Information
Page: /apex/OrgCheck_Batches_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Operating System: Win32
Language: es-ES

Error #0: EXCEEDED_ID_LIMIT
When: While creating a promise to call "private_query".
What:
index: 0
queryMore: undefined
queryString: SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, COUNT(Id) ids, SUM(NumberOfErrors) errors FROM AsyncApexJob WHERE ExtendedStatus <> NULL OR Status = 'Failed' GROUP BY JobType, ApexClass.Name, MethodName, Status, ExtendedStatus
queryUseTooling: false
EXCEEDED_ID_LIMIT: Aggregate query does not support queryMore(), use LIMIT to restrict the results to a single batch
   at h.getError (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:4:7059)

Error #1: TypeError
TypeError: Cannot read property 'm' of undefined
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615545379000/orgcheck__OrgCheck_OrgCheck_SR:1184:44


Thanks for checking!

**Comment by VinceFINET** [comment]
OK i see the issue.

It happens if you have a LOT of records in this query `SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, COUNT(Id) ids, SUM(NumberOfErrors) errors FROM AsyncApexJob WHERE ExtendedStatus <> NULL OR Status = 'Failed' GROUP BY JobType, ApexClass.Name, MethodName, Status, ExtendedStatus`

In that context, it means you have a lot of async jobs and the group by does not allow to query more than Xxx records.

First can you tell me what are you looking for in terms of AsyncJobs?
In this tab I intend to show only the failed one ordered by apex class/method.
Is it something you want? or you have something else in mind?? (while I am looking at this!!)

Thank you

**Comment by Nichneo** [comment]
Indeed we have a lot of async jobs, and the information I'd like to see is what you said, failed jobs with as much data as possible (e.g. why it failed, how many records failed, timestamps..)

**Comment by VinceFINET** [comment]
so may be the group by is not a good idea after all and I'll add a LIMIT as the error suggested....

**Comment by VinceFINET** [comment]
Hi @Nichneo 

Couple of options here, tell me what do you think? and test those queries in your org to check how many records are retrieved.

**Option 1: Additional filter to get only async apex jobs only from YESTERDAY**
The query will include a time filter for only yesterday information.
```
SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, COUNT(Id) ids, SUM(NumberOfErrors) errors 
FROM AsyncApexJob 
WHERE CompletedDate = YESTERDAY
AND (ExtendedStatus <> NULL 
OR Status = 'Failed') 
GROUP BY JobType, ApexClass.Name, MethodName, Status, ExtendedStatus
```

**Option 2: Make the code detect that you are running an aggregate query and not calling "queryMore" in that case.**
The impact is that you will not get information of next rows...
maybe need to have a flag to say that you have more records that you cannot fetch?? 

**Option 3: Remove the aggregate query and do the grouping in code, need to limit the number of records retrieved (with LIMIT)**
For example limit of 10000 records.... We could add also a time criteria as well.
```
SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, Id, NumberOfErrors 
FROM AsyncApexJob 
WHERE CompletedDate = YESTERDAY
AND (ExtendedStatus <> NULL 
OR Status = 'Failed')
LIMIT 10000
```

**Comment by Nichneo** [comment]
Hi @VinceFINET,
this is the result of first query:
![image](https://user-images.githubusercontent.com/49399608/111194392-71d38c00-85bb-11eb-8918-2e69c6ce5c07.png)
an this of second one:
![image](https://user-images.githubusercontent.com/49399608/111194581-a2b3c100-85bb-11eb-981e-25ede716a9cb.png)

I'd say that personally I'd like option 3, giving the possibility to limit either number or records or timeframe, and this because I know what is the amount of batches which I'm running each day, so I can control it.

**Comment by VinceFINET** [comment]
(edit)

What about **Option 4**?
```
SELECT JobType, ApexClass.Name, MethodName, Status, ExtendedStatus, COUNT(Id) ids, SUM(NumberOfErrors) errors
FROM AsyncApexJob
WHERE CompletedDate = YESTERDAY
AND ((Status = 'Completed' AND ExtendedStatus <> NULL)
OR Status = 'Failed')
GROUP BY JobType, ApexClass.Name, MethodName, Status, ExtendedStatus
LIMIT 10000
```
