### ISSUE TITLE
Custom Label does not show the dependency

### ISSUE THREAD

**Issue by areefabanu** [SalesforceLabs/OrgCheck#464]
Custom Label does not show the dependency for all references

**To Reproduce**
Goto -> 'Custom Label' tab from the navigation bar
On load of data, in the dependency section some show as dependency and some say " No Dependency" 
 
When i check for No dependency in org it has references for Apex and trigger.

Can you please help here.

Thank you !

**Comment by VinceFINET** [comment]
that issue was resolved part of the issue #465

**Comment by areefabanu** [comment]
I see this issue is working partially . some of the custom label it is showing dependency and some it is not showing.  can make it working fully functional.

**Comment by VinceFINET** [comment]
deployed!

**Comment by areefabanu** [comment]
Hi @VinceFINET , 

Quick question : When you say deployed.. is there anything we need to do from our side? like re-install package or update package?

I see the deployed solution is not working, i have attaches screen shot of warning.

All the lable in the attached screenshot is referring in Apex and lwc components.

The component  XXX (XXX) has a score of 1 because of the following reasons:
Not referenced anywhere: This component is not referenced anywhere (as we were told by the Dependency API). Please review the need to keep it in your org.

Can you please recheck  the issue once again.

Thank you!!

**Comment by VinceFINET** [comment]
can you give me:
- the orgid of the salesforce org where you see this issue
- the id of a custom label that does work
- the id of a custom label that does NOT work 

org id starts with 00D
custom label id starts with 101

thank you

**Comment by VinceFINET** [comment]
note: the attachment in your email were not sent to github. i don't see any screenshot yet. can you share it again here?

**Comment by VinceFINET** [comment]
any update on this one @areefabanu ?

**Comment by areefabanu** [comment]
Hi @VinceFINET , 

Its working now. thank you for the fix. We can close this issue.

Thanks you!!
