### ISSUE TITLE
Can not accept terms

### ISSUE THREAD

**Issue by pipetopic** [SalesforceLabs/OrgCheck#468]
**Describe the bug**
I installed Orgcheck and opened the site in Salesforce. Two messages appear:
**First message:**
_Wait a minute!_
_You are using the application in Production._

_Please accept to terms of conditions for direct usage in production by changing the filter "Do you confirm running Org Check in production?" to YES._

_Thank you and have a nice day!_

**Second Message:**
_Org Check is spinning around for 1.026 seconds. ..._

All boxes in thesecond screen are green but I can not close this screen to accept the terms mentioned in the first screen.

**To Reproduce**
Reinstall the package and open the Home Page.

**Comment by VinceFINET** [comment]
thanks for this issue

I believe you have something similar to this
<img width="1733" alt="image" src="https://github.com/user-attachments/assets/bbe94f7e-4953-48fe-b027-4594a1dcd5e6">

and then 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/6ab9e8a7-b333-4e44-981a-0b1561e6ae95">

**Comment by pipetopic** [comment]
Yes the other way around. I can close the "Wait a minute"-screen but then the other screen (Org Check is spinning around...) blocks the rest of the site. 
Or do I just have to wait longer? I already waited for over half an hour.

**Comment by VinceFINET** [comment]
As a workaround, i suggest you use the app in a sandbox.

In terms of fix/solution, I will work on the following:
- the overlaping modals are not so good, so need a better user experience
- you should be able to have access to this option in the error message dialog instead of the home screen (which is unaccessible). so at least make that option possible accessible from the modal. or a button to say "i accept" or similar.
- you could keep that option on the home screen to switch back to "i dont accept" but that is somehow weird so maybe that option only needs to be in that specific dialogbox after all!

i will deliver this fix next week.

**Comment by pipetopic** [comment]
Thank you very much for the quick response. Beeing able to accept the terms in the error message would help a lot. 
I will wait till it is fix. Will you add an update to this post once its solved?

**Comment by VinceFINET** [comment]
of course yes i'll do that.

**Comment by VinceFINET** [comment]
Proposal:

![image](https://github.com/user-attachments/assets/92d8e0bc-cdf1-4bd3-9efd-d5e20a2f50cc)
then close the modal

if i go to another tab without accepting the terms i get the same modal again and again
![image](https://github.com/user-attachments/assets/06032638-9523-4b2b-8bad-7c63d4cc1c71)

Then i finally accept the terms
<img width="519" alt="image" src="https://github.com/user-attachments/assets/bccb6762-8ab8-4cd2-b83f-59f8b1d22785">

Apply it
<img width="626" alt="image" src="https://github.com/user-attachments/assets/02371329-8793-451a-8598-b38648d69819">

Then app starts to gather data from the org and finally display here the graph for role hierarchy (example of course)
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/312c4f3d-051c-4b43-9bf1-19727db40307">

Reset button in the global filter will put the acceptance back to No and you will have the modal again.
But the cache wont be deleted.

WHAT DO YOU SAY??

**Comment by pipetopic** [comment]
I can not change tabs within Org Check because the screen blocks everything. This is what I am stuck with:
![image](https://github.com/user-attachments/assets/ee39f9b4-7cc3-445c-93a5-4f6334e08def)

**Comment by venkatamahadevan** [comment]
Thanks a lot for hte proposal Vincent. I have the same issue with my customer and I think your proposal does the work for me and my customer. 

Thanks and Regards
MV

**Comment by VinceFINET** [comment]
ok so another proposal (which i prefer) will be:

if production org then you have this home tab:
<img width="1753" alt="image" src="https://github.com/user-attachments/assets/fd90a116-e93c-4087-866d-24cb1bbc4ee2">

You need to enable this option:
<img width="486" alt="image" src="https://github.com/user-attachments/assets/74c62a1a-824a-4f2a-93a6-a79d41b99e9d">

Then the usual page is loading
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/1cb2ba25-ca96-47e9-ad4d-275c75c4a1fe">

**Comment by pipetopic** [comment]
Thank you. That sounds very good. Do I have to reinstall org check in order to use this feature or does it update automatically?

**Comment by cbenitezSFDC** [comment]
Hi, I have seen that this issue is closed but I still have the same problem regarding the pop up. I have uninstall and reinstall again the package but still pops up. When is it going to be fixed? Thanks in advance.

**Comment by VinceFINET** [comment]
that will be released in couple of days. I will let you know. thank you you for your patience.

**Comment by VinceFINET** [comment]
deployed !
