### ISSUE TITLE
Org check in the loop not letting check anything

### ISSUE THREAD

**Issue by cbenitezSFDC** [SalesforceLabs/OrgCheck#470]
**Describe the bug**
In the production org, the Org Check is spinning around without stopping.
**To Reproduce**
This is the error:
![image](https://github.com/user-attachments/assets/1dc86b8f-c1d2-4b70-ac87-782abf9d76f4)

**Comment by VinceFINET** [comment]
Duplicate of #468

**Comment by VinceFINET** [comment]
deployed !
