### ISSUE TITLE
bug - key permissions under users tab

### ISSUE THREAD

**Issue by pritaunk** [SalesforceLabs/OrgCheck#50]
Under the **Active Users Profile and Permissions Overview** on the users tab, when analysing my org, i identified that some of the key permissions listed below is not reflecting for a profile I know has modify all and view all data. it only shows View set up.  Maybe the below info is not being picked up? or is this info only being picked up via permission set, and not profile?

The KEY PERMISSIONS is showing if a user has one of the following system permissions:
apiEnabled: Api Enabled,
viewSetup: View Setup,
modifyAllData: Modify All Data,
viewAllData: View All Data.

**Comment by VinceFINET** [comment]
Reproduced in my org
I am a system admin and I see only the two following permissions:
![image](https://user-images.githubusercontent.com/3799275/111519457-687f2680-8757-11eb-90b5-626a6081db5b.png)

So the bug might be around the Modify All Data and View All Data permissions

**Comment by VinceFINET** [comment]
Ok i found the error.
I am listing only the permissions that are given via permission set not via the profiles

**Comment by VinceFINET** [comment]
Corrected!!! Very good catch AGAIN !!!!
![image](https://user-images.githubusercontent.com/3799275/111521888-f3f9b700-8759-11eb-995a-ce55a3540560.png)

**Comment by pritaunk** [comment]
🎉🎉
