### ISSUE TITLE
Profiles and Permissions/Number of users

### ISSUE THREAD

**Issue by pritaunk** [SalesforceLabs/OrgCheck#51]
On the **Profiles and Permissions** tab, under **Profiles**,  on the Number of users column (or a new column), it might be useful to reflect how many out of those users are active/inactive.

**Comment by VinceFINET** [comment]
You are totally right currently all users are part of this counter whatever if they are active or not.
This is the case for profiles but also for permission sets.

I would say it should be only active users.
So the solution would be to add simply a criteria to get only the active users that are assigned for profiles and permission sets.

What do you say? @pritaunk 

This is here in the code for profiles:
![image](https://user-images.githubusercontent.com/3799275/111503216-d707b880-8746-11eb-8eb4-ad40c9e3cba7.png)

This is here in the code for permission sets:
![image](https://user-images.githubusercontent.com/3799275/111503399-028aa300-8747-11eb-8175-c903b01c0e6c.png)

**Comment by VinceFINET** [comment]
Done!! 

For profiles:
![image](https://user-images.githubusercontent.com/3799275/111518784-b3e50500-8756-11eb-9fb8-25ad466ef801.png)

For permission sets:
![image](https://user-images.githubusercontent.com/3799275/111518871-cb23f280-8756-11eb-9fa0-be93a755d115.png)

Thank you for this.
Very good catch.
At the same I added some improvements around error handling!

**Comment by pritaunk** [comment]
Awesome! Thanks Vince.
Loving using this app!!
