### ISSUE TITLE
In the Object tab, I need to know if an object is "used"

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#55]
Once the object is selected
Get the date/time of the most recent record.
(use lastmod because it is indexed)
Compare it to TODAY
If more than XX days then alert !

Need to specify on the "XX" (number of days)

**Comment by dschach** [comment]
Feature request on this: Include total number of records. (This will burn a lot of SOQL queries, so perhaps do this in a batch.)
It might be best to limit this to objects that count against storage usage (all custom objects, for example) and not those that do not count (Chatter objects, for example)

**Comment by VinceFINET** [comment]
You can have the record count with the rest api

**Comment by VinceFINET** [comment]
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_record_count.htm

**Comment by VinceFINET** [comment]
I logged a ticket to see if this request is possible via JsForce see https://github.com/jsforce/jsforce/issues/1145

**Comment by VinceFINET** [comment]
As for the record count on the object level:
![image](https://user-images.githubusercontent.com/3799275/121169262-1c261d00-c854-11eb-86e2-5e5b1b805090.png)
