### ISSUE TITLE
Custom Field Tab ignores formulas

### ISSUE THREAD

**Issue by vaumont** [SalesforceLabs/OrgCheck#59]
It seems that formulas are not included in the Custom Fields list.

**Comment by VinceFINET** [comment]
Hi Vincent

Actually, it is including formulas but only if they are not from a package.

The query is:
```
SELECT Id, TableEnumOrId, DeveloperName, NamespacePrefix 
FROM CustomField 
WHERE ManageableState = 'unmanaged'
```

Are you aligned with that?

**Comment by vaumont** [comment]
My bad - it was a bug in my script.
