### ISSUE TITLE
Standard fields counted as custom fields (twice) 

### ISSUE THREAD

**Issue by vaumont** [SalesforceLabs/OrgCheck#64]
I have a custom field on Opportunity named Amount__c
OrgScore shows me 3 'Amount' custom fields, with different usages.

Also: the following Opportunity fields, despite being standard fields, are listed as custom fields twice:
CloseDate
ForecastCategoryName
Probability
StageName

**Comment by VinceFINET** [comment]
I don't know about **OrgScore** (which might be another tool I presume) but **OrgCheck** in this tab is ONLY listing custom fields and not standard fields.

I did a quick test, and after adding a custom field "`Amount__c`" on "`Opportunity`", it shows the field as follow:
![image](https://user-images.githubusercontent.com/3799275/112465881-7f300980-8d65-11eb-8d8f-3e4bad77c446.png)

With the following dependencies:
![image](https://user-images.githubusercontent.com/3799275/112465964-97078d80-8d65-11eb-93c1-3398aa08218a.png)

For the second part of your question, again **OrgCheck** is only listing custom fields and not standard ones.

**Comment by vaumont** [comment]
Sorry, I meant OrgCheck.
Here are some screenshots of the Custom Fields tab:

![image](https://user-images.githubusercontent.com/58858217/112575770-35b7dc80-8dae-11eb-9abd-76df9239a113.png)
![image](https://user-images.githubusercontent.com/58858217/112575834-56803200-8dae-11eb-8620-3e380f381f6c.png)
![image](https://user-images.githubusercontent.com/58858217/112575913-79aae180-8dae-11eb-8683-78f5637f9777.png)
![image](https://user-images.githubusercontent.com/58858217/112575936-8596a380-8dae-11eb-8913-c12cde7384f2.png)

**Comment by VinceFINET** [comment]
After a call with @vaumont and me, we discovered that the issue is in link with the use of custom metadata type.
In the previous example, the "Opportunity" object here is a custom metadata type and not a custom object.

I reproduced the error with a custom metadata type called "Opportunity" and a custom field "Amount" (text) on this cmt.
<img src="https://user-images.githubusercontent.com/3799275/113176211-86b34f00-924c-11eb-853b-73dee8a200bc.png" width="30%" />

In this case visually you don't see the difference between the object and the custom metadata type.

I would say:
- add a column in the table to say if the "container" of the custom field is a "`Standard Object`", "`Custom Object`" or "`Custom Metadata Type`"
- make sure the link to the "container" is working (depending on its type for example)
- make sure the link to the "field" is working as well

**Comment by VinceFINET** [comment]
Little fun here for the test, I created:
- a custom field called "Amount" on the standard "Opportunity"
- a CustomMetadataType called "Opportunity" with a field called "Amount"
- a CustomSetting called "Opportunity2" (can't use a name already used by another entity) with a field called "Amount"
- an ExternalObject called "Opportunity3" (can't use a name already used by another entity) with a field called "Amount" 

At this stage it looks like this:
<img src="https://user-images.githubusercontent.com/3799275/113436184-8ea5f700-93e4-11eb-92c2-08fd1a126bc2.png" width="30%" style="max-width:100%;">

**Comment by VinceFINET** [comment]
In this case:

Let's list the `Amount` custom fields in `CustomField` table. The "amazing" (let's call it that way) column called `TableEnumOrId` is an id if custom (starting with 01I) or API name if standard object.
```
SELECT Id, DeveloperName, TableEnumOrId 
FROM CustomField 
WHERE ManageableState='unmanaged' 
AND DeveloperName LIKE '%Amount%'

ID                  DEVELOPERNAME  TABLEENUMORID
──────────────────  ─────────────  ──────────────────
00N3V000000UiUOUA0  Amount         Opportunity
00N3V000000UiJGUA0  Amount         01I3V000000DFgZUAW
00N3V000000UhC9UAK  Amount         01I3V000000DFdkUAG
00N3V000000UiUJUA0  Amount         01I3V000000DFgeUAG
```

The `EntityDefinition` contains information to guess the type of the "container" in the `QualifedApiName` (only the prefix) and the `IsCustomSetting` (to distinguish custom obj and custom settings)
```
SELECT DeveloperName, DurableId, IsCustomSetting, QualifiedApiName  
FROM EntityDefinition 

DEVELOPERNAME  DURABLEID        ISCUSTOMSETTING  QUALIFIEDAPINAME
─────────────  ───────────────  ───────────────  ────────────────
Opportunity2   01I3V000000DFgZ  true             Opportunity2__c 
Opportunity3   01I3V000000DFge  false            Opportunity3__x 
Opportunity    01I3V000000DFdk  false            Opportunity__mdt
```

The custom object contains very few information we cannot distinguish the type...
```
SELECT Id, DeveloperName 
FROM CustomObject 
WHERE DeveloperName LIKE 'Opportunity%'

ID                  DEVELOPERNAME
──────────────────  ─────────────
01I3V000000DFgZUAW  Opportunity2
01I3V000000DFdkUAG  Opportunity
01I3V000000DFgeUAG  Opportunity3
```


So I would go with this pseudo algo:
```
List the custom field from **CustomField** and get the column **TableEnumOrId**.
IF (the **TableEnumOrId** DOES NOT start with **'01I'**) THEN {
    >> The container is a "Standard Object"
} ELSE {
    Look at the **TableEnumOrId** in **EntityDefinition**
    IF (**IsCustomSetting** = **'true'**) THEN {
        >> The container is a "Custom Setting"
    } ELSE {
        IF (**QualifiedApiName** endsWith **'__c'**) THEN {
             >> The container is a "Custom Object"
        } ELSE IF (**QualifiedApiName** endsWith **'__x'**) THEN {
             >> The container is a "External Object"
        } ELSE IF (**QualifiedApiName** endsWith **'__mdt'**) THEN {
             >> The container is a "Custom Metadata Type"
        } ELSE IF {
             >> The container is a "Custom Entity We Don't Know Yet..."
        }
    }
}
```

**Comment by VinceFINET** [comment]
Done @vaumont !!!

Look at this!
![image](https://user-images.githubusercontent.com/3799275/113443432-442b7700-93f2-11eb-8034-54936c664fa5.png)

And the link to the object (or "container") is also dynamic!

Thanks for your feedback!!
