### ISSUE TITLE
Apex Class search only matches on full search term

### ISSUE THREAD

**Issue by pgonzaleznetwork** [SalesforceLabs/OrgCheck#66]
On the apex classes page, I cannot find the apex class `CS_ReleaseSupportExpirationDates` by any of the following

`CS_Release`
`Expiration`

I can only find it if I type in the entire name.

It'd be great if the search matched on any characters.

**Comment by pgonzaleznetwork** [comment]
Also it'd be great if it wasn't case sensitive, because then even if you know the full name of the class, one character having the wrong case will prevent the search from finding it. This means that I'd have to go find the class in setup/vscode, copy and paste the name, which is not ideal.

**Comment by VinceFINET** [comment]
Thank you for your feedback on OrgCheck!!


Well, it's working as expected.
I created an empty class with the same name
You have to type the search item **and then** press enter to make it work.

As it is written in the field you see?
<img src="https://user-images.githubusercontent.com/3799275/113447039-5eb51e80-93f9-11eb-87c8-10e57808ba17.png" width="40%" />



But I do agree with you the case-sensitive thing is kind of frustrating! 
i will change this!
