### ISSUE TITLE
Missed dependencies

### ISSUE THREAD

**Issue by vaumont** [SalesforceLabs/OrgCheck#69]
I noticed that OC reports some fields has having no dependencies when, in fact, they do.
This might have to do with the large number of fields on the object (the Lead object has 700 fields)  or the high number of reports in the org (93k)

Ex: The Favorite_Music field on the Lead object is used in report types and report (and nowhere else), yet OrgCheck reports no usage:

![image](https://user-images.githubusercontent.com/58858217/113468596-e6039180-93fb-11eb-83c7-2df770494f76.png)

![image](https://user-images.githubusercontent.com/58858217/113468613-06335080-93fc-11eb-9e98-13463deb0466.png)

**Comment by VinceFINET** [comment]
Is it due to Dependency API not returning anything???
Can you try to call the DAPI directly from Tooling API in this particular case.
If it returns nothing this is a limitation of the DAPI 
If it returns something then I am missing something...

**Comment by vaumont** [comment]
@VinceFINET 

There are 13 MetadataComponentDependency rows for that field. 

SELECT  RefMetadataComponentId , RefMetadataComponentNamespace , 
                           RefMetadataComponentName , RefMetadataComponentType, 
                           MetadataComponentId,     MetadataComponentNamespace,     
                           MetadataComponentName, MetadataComponentType
                           FROM MetadataComponentDependency
                           where RefMetadataComponentType = 'CustomField'
                           and RefMetadataComponentId='00Nb0000009Oe0lEAC'                                                                            
                           and RefMetadataComponentNamespace = ''

![image](https://user-images.githubusercontent.com/58858217/113763629-bdff8100-96ce-11eb-9fc3-76d42f1d7479.png)

**Comment by VinceFINET** [comment]
This is due i think to the way the tool is calling the DAPI I think. 
currently the tool is calling 50 by 50 ids in the query:
![image](https://user-images.githubusercontent.com/3799275/114598717-82e2ec00-9c92-11eb-812c-a6cfb25bdfa9.png)

So basically if, for example, the first 48 ids are already referenced in 1990 items, that does not give much space for the two remaining id in the query. in that case you may experience missing references in the query and in the screen.... REALLY GOOD catch !!!

As there is another ticket that excludes now the report type maybe the 2000 lines return max will not be reached.
Maybe i can work on using the bulkAPI with JsForce 1.10 and hopefully make it work this time (jsforce 1.9 had a known bug for bulk api).
