### ISSUE TITLE
Add reports, dashboards and custom report types in the app

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#7]

**Comment by jalal3107** [comment]
Very useful

**Comment by VinceFINET** [comment]
i need to push than (again) for the next release! but that will be on top priority for 1.9.6!!!

**Comment by VinceFINET** [comment]
First version of the "Analytics" tab:
![image](https://user-images.githubusercontent.com/3799275/145447894-772eb617-4b44-4d0c-b274-cc3351048b5c.png)

For now only the reports and dashboards.
I discover that custom report types are only available from Metadata API ;)
Plus you can't have from REST API (SOQL query i mean) the custom report type used for a specific report. you can use the analytics api, but how complex is it !! and of course one by one !!!
Pffff....
