### ISSUE TITLE
Yellow in table

### ISSUE THREAD

**Issue by VinceFINET** [SalesforceLabs/OrgCheck#89]
Could it be possible to have not all the row in yellow when the SCORE is > 0, instead, just put the SCORE cell in yellow and also the cell that had a problem; and let the others without any coloration.

This might be more readable.

Idea from @nono26152

**Comment by VinceFINET** [comment]
Which one do you like the best?

Scenario 1:
![image](https://user-images.githubusercontent.com/3799275/119866417-14de4580-bf1d-11eb-8efa-29cc84e408fa.png)

Scenario 2:
![image](https://user-images.githubusercontent.com/3799275/119866528-317a7d80-bf1d-11eb-9b0c-62e51caa5612.png)

Scenario 3:
![image](https://user-images.githubusercontent.com/3799275/119867092-cc735780-bf1d-11eb-9cb2-8700e61f0cda.png)

**Comment by ArnaudCeyrac** [comment]
In my opinion the clearer one is Scenario 2.
--
Arnaud Ceyrac

**Comment by VinceFINET** [comment]
I created a poll in slack let see what the other users say!!!

**Comment by VinceFINET** [comment]
Another option would be: 
![image](https://user-images.githubusercontent.com/3799275/119978789-583ac180-bfba-11eb-8f78-71b4230cad68.png)
