### ISSUE TITLE
déterminer les classes de test relatives a une classe Apex

### ISSUE THREAD

**Issue by ochemaou** [SalesforceLabs/OrgCheck#91]
Est-il possible d'avoir à partir d'une classe Apex toutes les classes de test qui doivent être embarqués avec la classe Apex?

**Comment by VinceFINET** [comment]
Translation: is it possible to list the apex unit test classes that are testing a given class?

**Comment by VinceFINET** [comment]
Two approaches:
- using the DAPI? but what if you have multiple layer of classes??? so not easy to implement.
- using the TestAggregates after running all classes. Much easier to implement and better results.

The idea would be to ask you to run all the apex unit test in the org.
And after that, I can check which Apex Unit Test is covering which Apex Class.

What do you think of this @ochemaou ???

**Comment by VinceFINET** [comment]
![image](https://user-images.githubusercontent.com/3799275/119569880-a760d680-bdaf-11eb-81b5-d45905e0aaf2.png)

**Comment by ochemaoutrail** [comment]
we run every day all test classes so it will be ok for us
thanks

**Comment by VinceFINET** [comment]
@ochemaoutrail this feature will be available soon in 1.9.5
