### ISSUE TITLE
OWD - add csv export and Label and full API name

### ISSUE THREAD

**Issue by sfshiest** [SalesforceLabs/OrgCheck#95]
Would it be possible to add the full object API Name (and the Object label - optional) to the OWD tab?
Also, would it be possible to have a CSV export capability?

**Comment by VinceFINET** [comment]
Done as part of future 1.9.4

See screen shot below:
![image](https://user-images.githubusercontent.com/3799275/118529212-8b23c080-b743-11eb-847a-dc828039fbeb.png)
