### ISSUE TITLE
Blank batch page

### ISSUE THREAD

**Issue by Nichneo** [SalesforceLabs/OrgCheck#96]
Hi Vincent, somehow the Batch page for me is shown as blank, despite the cache has 34 batches:
![image](https://user-images.githubusercontent.com/49399608/118934050-33a37180-b94a-11eb-9594-5bc1f85314e3.png)
![image](https://user-images.githubusercontent.com/49399608/118934087-3f8f3380-b94a-11eb-972b-c88e9e1f013b.png)
I tried with Chrome and Firefox, in case it could be a browser problem.

**Comment by VinceFINET** [comment]
Interesting!
I will investigate thank you for this, @Nichneo !!

**Comment by VinceFINET** [comment]
@Nichneo Very good catch! 
In the code of the **Batches** page, I was getting a datastore that was always empty !!

**Comment by VinceFINET** [comment]
I changed also the criteria of the queries that were getting info from YESTERDAY but not TODAY.
It was kind of complicated for my own test.
I will include (if you don't mind @Nichneo) in this page the batches and scheduled jobs that had an issue from YESTERDAY to the PRESENT day (including today then).

**Comment by VinceFINET** [comment]
And improved also that page which was mixing scheduled jobs and apex jobs.
